CREATE TABLE `service_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`email` varchar(320) NOT NULL,
	`usedBefore` varchar(8),
	`firstName` varchar(128) NOT NULL,
	`lastName` varchar(128) NOT NULL,
	`phone` varchar(32) NOT NULL,
	`siteAddress` text NOT NULL,
	`billingAddress` text,
	`howHeard` text,
	`serviceType` varchar(128) NOT NULL,
	`warrantyDetails` text,
	`salesConsultant` varchar(128),
	`projectManager` varchar(128),
	`maintenanceTypes` text,
	`maintenanceNotes` text,
	`irrigationTypes` text,
	`irrigationNotes` text,
	`winterizationDate` varchar(32),
	`lightingTypes` text,
	`lightingNotes` text,
	`waterFeatureTypes` text,
	`waterFeatureNotes` text,
	`waterFeatureRepairDesc` text,
	`creditCardNumber` varchar(32),
	`creditCardExpiration` varchar(16),
	`creditCardCvv` varchar(8),
	`creditCardAuthSignature` text,
	`concreteServiceType` varchar(64),
	`concreteElements` text,
	`concreteDimensions` text,
	`concreteHasStairs` varchar(8),
	`concreteAttachedToBuilding` varchar(16),
	`hasExistingDesign` varchar(8),
	`needsHoaApproval` varchar(16),
	`landscapeElements` text,
	`budget` varchar(32),
	`budgetOther` varchar(64),
	`designConsultationAccepted` varchar(64),
	`idealCompletionDate` varchar(32),
	`flexibleScheduling` boolean DEFAULT false,
	`isRentalProperty` varchar(8),
	`isPropertyOwner` varchar(8),
	`hasPets` varchar(8),
	`comments` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `service_submissions_id` PRIMARY KEY(`id`)
);
