// AUTO-GENERATED by gen_route_meta.py — DO NOT EDIT MANUALLY
// Maps URL pathname → { title, canonical, description } for SSR head injection

export interface RouteMeta {
  title: string;
  canonical: string;
  description: string;
}

export const routeMeta: Record<string, RouteMeta> = {
  '/': {
    title: 'Landscaping Company Bend Oregon | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/',
    description: 'Central Oregon\'s premier landscaping company since 2005. Custom landscape design, installation, maintenance & irrigation in Bend, Redmond, Sisters & beyond.',
  },
  '/about': {
    title: 'About Newport Avenue Landscaping | Bend, Oregon Since 2005',
    canonical: 'https://www.newportavelandscaping.com/about',
    description: 'Meet Sterling West and the Newport Avenue team — Central Oregon\'s most experienced full-service landscape contractor. 150+ professionals, 21+ years serving Bend, OR. LCB #9153.',
  },
  '/blog': {
    title: 'Landscaping Blog | Central Oregon Tips & Guides | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/blog',
    description: 'Expert landscaping guides for Central Oregon homeowners: xeriscaping, irrigation, pavers, lawn care, fire features & seasonal maintenance tips from Newport Avenue Landscaping.',
  },
  '/blog/lawn-care-bend-oregon': {
    title: 'Lawn Care in Bend Oregon — Complete Seasonal Guide | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/blog/lawn-care-bend-oregon',
    description: 'The complete guide to lawn care in Bend, Oregon. Watering schedules, fertilization timing, aeration, overseeding, and weed control for Central Oregon\'s high desert climate.',
  },
  '/blog/paver-patio-ideas-bend-oregon': {
    title: 'Paver Patio Ideas Bend Oregon — Design Inspiration | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/blog/paver-patio-ideas-bend-oregon',
    description: 'Paver patio design ideas for Bend, Oregon homes. Belgard & Unilock paver styles, layout patterns, fire pit integration & outdoor kitchen ideas for Central Oregon\'s lifestyle.',
  },
  '/blog/sprinkler-winterization-bend-oregon': {
    title: 'Sprinkler Winterization Bend Oregon — When & Why | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/blog/sprinkler-winterization-bend-oregon',
    description: 'When to winterize your sprinklers in Bend, Oregon, what happens if you don\'t, and how Newport Avenue Landscaping\'s certified technicians protect your system every fall.',
  },
  '/blog/xeriscape-landscaping-bend-oregon': {
    title: 'Xeriscape Landscaping Bend Oregon — Complete Guide | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/blog/xeriscape-landscaping-bend-oregon',
    description: 'Everything you need to know about xeriscape landscaping in Bend, Oregon. Drought-tolerant plants, design principles & cost savings for Central Oregon\'s high desert climate.',
  },
  '/careers': {
    title: 'Careers at Newport Avenue Landscaping | Bend, Oregon',
    canonical: 'https://www.newportavelandscaping.com/careers',
    description: 'Join Central Oregon\'s most qualified landscaping team. Newport Avenue Landscaping is hiring irrigation technicians, crew leads, designers, and construction crew members in Bend, OR.',
  },
  '/commercial': {
    title: 'Commercial Landscaping Bend Oregon | HOA & Property Management',
    canonical: 'https://www.newportavelandscaping.com/commercial',
    description: 'Commercial landscaping, HOA maintenance & property management services in Central Oregon. Newport Avenue manages more HOA contracts than any other firm. LCB #9153. Free bid.',
  },
  '/contact': {
    title: 'Contact Newport Avenue Landscaping | Free Quote Bend, Oregon',
    canonical: 'https://www.newportavelandscaping.com/contact',
    description: 'Request a free landscaping quote in Bend, Redmond, or Tumalo, Oregon. Call (541) 617-8873 or submit online — we respond within 1 business day. LCB #9153.',
  },
  '/landscaping/alfalfa': {
    title: 'Alfalfa Oregon Landscaping & Lawn Care | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/landscaping/alfalfa',
    description: 'Newport Avenue Landscaping serves Alfalfa, Oregon with expert landscaping, irrigation, and lawn care for rural and acreage properties. Free estimates. LCB #9153.',
  },
  '/landscaping/bend': {
    title: 'Bend Landscaping Oregon & Bend Lawn Care | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/landscaping/bend',
    description: 'Newport Avenue Landscaping offers premier landscaping and lawn care services in Bend, Oregon. With LCB #9153, we provide free estimates for all your outdoor needs.',
  },
  '/landscaping/cline-falls': {
    title: 'Cline Falls Oregon Landscaping & Lawn Care | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/landscaping/cline-falls',
    description: 'Newport Avenue Landscaping serves Cline Falls, Oregon with expert landscaping, irrigation, and lawn care. Specialists in Deschutes River corridor properties. Free estimates. LCB #9153.',
  },
  '/landscaping/crooked-river-ranch': {
    title: 'Crooked River Ranch Landscaping & Lawn Care | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/landscaping/crooked-river-ranch',
    description: 'Newport Avenue Landscaping delivers expert landscaping, irrigation, and lawn care services to Crooked River Ranch, Oregon. High-desert specialists. Free estimates. LCB #9153.',
  },
  '/landscaping/eagle-crest': {
    title: 'Eagle Crest Landscaping Oregon | Lawn Care & Design in Eagle Crest Resort',
    canonical: 'https://www.newportavelandscaping.com/landscaping/eagle-crest',
    description: 'Newport Avenue Landscaping serves Eagle Crest Resort and residential properties in Redmond, Oregon. Expert landscape design, irrigation, xeriscaping, and seasonal maintenance for high-desert resort living. LCB#9153. Free estimates.',
  },
  '/landscaping/la-pine': {
    title: 'La Pine Landscaping Oregon | La Pine Lawn Care | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/landscaping/la-pine',
    description: 'Newport Avenue Landscaping offers premier landscaping and lawn care services in La Pine, Oregon. Cold-hardy design, irrigation, xeriscaping, and maintenance for South Deschutes County. LCB #9153. Free estimates.',
  },
  '/landscaping/madras': {
    title: 'Madras Landscaping Oregon | Professional Lawn Care & Design | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/landscaping/madras',
    description: 'Premier Madras landscaping and lawn care services by Newport Avenue Landscaping. LCB #9153. Custom design, irrigation, xeriscaping, and maintenance for Jefferson County properties. Free estimates.',
  },
  '/landscaping/powell-butte': {
    title: 'Powell Butte Landscaping Oregon | Lawn Care & Design for Rural Properties',
    canonical: 'https://www.newportavelandscaping.com/landscaping/powell-butte',
    description: 'Newport Avenue Landscaping serves Powell Butte, Oregon with expert landscaping for rural ranches, farms, and horse properties. Irrigation, fire-wise design, xeriscaping, and large-lot maintenance. LCB#9153. Free estimates.',
  },
  '/landscaping/prineville': {
    title: 'Prineville Landscaping Oregon | Prineville Lawn Care Services',
    canonical: 'https://www.newportavelandscaping.com/landscaping/prineville',
    description: 'Newport Avenue Landscaping offers premier lawn care, landscape design, and irrigation services in Prineville, Oregon. LCB#9153. Get your free estimate today!',
  },
  '/landscaping/redmond': {
    title: 'Redmond Landscaping Oregon | Redmond Lawn Care | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/landscaping/redmond',
    description: 'Transform your Redmond property with Newport Avenue Landscaping. We offer expert lawn care, landscape design, and irrigation services. LCB#9153. Free estimates!',
  },
  '/landscaping/sisters': {
    title: 'Sisters Landscaping Oregon | Sisters Lawn Care & Design - Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/landscaping/sisters',
    description: 'Transform your Sisters, Oregon property with Newport Avenue Landscaping. We offer comprehensive lawn care, design, and irrigation services. LCB#9153. Get a free estimate today!',
  },
  '/landscaping/sunriver': {
    title: 'Sunriver Landscaping Oregon | Premier Sunriver Lawn Care & Design',
    canonical: 'https://www.newportavelandscaping.com/landscaping/sunriver',
    description: 'Newport Avenue Landscaping offers premier landscaping and lawn care in Sunriver, Oregon. Expert design, installation, and maintenance tailored for high-desert conditions. LCB#9153. Free estimates.',
  },
  '/landscaping/terrebonne': {
    title: 'Terrebonne Landscaping Oregon & Terrebonne Lawn Care | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/landscaping/terrebonne',
    description: 'Newport Avenue Landscaping provides professional landscaping, irrigation, and lawn care services in Terrebonne, Oregon. Serving the Crooked River Ranch area and all of Jefferson County. Free estimates. LCB #9153.',
  },
  '/landscaping/tumalo': {
    title: 'Tumalo Landscaping Oregon & Tumalo Lawn Care Experts | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/landscaping/tumalo',
    description: 'Newport Avenue Landscaping offers premier landscaping and lawn care services in Tumalo, Oregon. From design to maintenance, get a free estimate today! LCB #9153.',
  },
  '/maintenance': {
    title: 'Lawn Care Bend Oregon | Mowing, Cleanup & Maintenance | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/maintenance',
    description: 'Bend Oregon\'s lawn care experts since 2005. Weekly mowing from $97/service, spring & fall cleanups, sprinkler maintenance, snow removal & full-service landscape maintenance programs. LCB #9153.',
  },
  '/maintenance/commercial-hoa': {
    title: 'Commercial & HOA Landscape Maintenance Bend Oregon | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/maintenance/commercial-hoa',
    description: 'Ongoing commercial and HOA landscape maintenance in Bend, Oregon. Weekly mowing, seasonal cleanups, irrigation management, and snow removal for office parks, retail centers, and master-planned communities. LCB #9153.',
  },
  '/membership': {
    title: 'Priority Irrigation Membership | Newport Avenue Landscaping Bend',
    canonical: 'https://www.newportavelandscaping.com/membership',
    description: 'Newport Avenue\'s Priority Irrigation Membership — guaranteed spring activation, fall blowout, mid-season checks & 1-year warranty on irrigation components. Bend, OR. LCB #9153.',
  },
  '/our-work': {
    title: 'Our Work | Landscaping Portfolio Bend Oregon | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/our-work',
    description: 'Browse Newport Avenue Landscaping\'s project portfolio — paver patios, custom backyard designs, water features & commercial installs in Bend, OR. Real photos from real Central Oregon projects.',
  },
  '/portfolio/awbrey-butte-xeriscape': {
    title: 'Awbrey Butte Xeriscape',
    canonical: 'https://www.newportavelandscaping.com/portfolio/awbrey-butte-xeriscape',
    description: '',
  },
  '/portfolio/backyard-renovation': {
    title: 'Backyard Landscape Renovation',
    canonical: 'https://www.newportavelandscaping.com/portfolio/backyard-renovation',
    description: '',
  },
  '/portfolio/bend-full-yard-transformation': {
    title: 'Bend Full Yard Transformation',
    canonical: 'https://www.newportavelandscaping.com/portfolio/bend-full-yard-transformation',
    description: '',
  },
  '/portfolio/broken-top-water-feature': {
    title: 'Broken Top Water Feature & Sunken Fire Pit',
    canonical: 'https://www.newportavelandscaping.com/portfolio/broken-top-water-feature',
    description: '',
  },
  '/portfolio/broken-top-xeriscape': {
    title: 'Broken Top Xeriscape',
    canonical: 'https://www.newportavelandscaping.com/portfolio/broken-top-xeriscape',
    description: '',
  },
  '/portfolio/century-drive': {
    title: 'Century Drive Landscape Enhancement',
    canonical: 'https://www.newportavelandscaping.com/portfolio/century-drive',
    description: '',
  },
  '/portfolio/east-bend-landscape': {
    title: 'East Bend Landscape Install',
    canonical: 'https://www.newportavelandscaping.com/portfolio/east-bend-landscape',
    description: '',
  },
  '/portfolio/nw-bend-backyard': {
    title: 'NW Bend Backyard Landscaping',
    canonical: 'https://www.newportavelandscaping.com/portfolio/nw-bend-backyard',
    description: '',
  },
  '/portfolio/nw-bend-lighting': {
    title: 'NW Bend Landscape Lighting',
    canonical: 'https://www.newportavelandscaping.com/portfolio/nw-bend-lighting',
    description: '',
  },
  '/portfolio/paver-patio-firepit': {
    title: 'Paver Patio & Gas Firepit',
    canonical: 'https://www.newportavelandscaping.com/portfolio/paver-patio-firepit',
    description: '',
  },
  '/portfolio/sw-bend-backyard': {
    title: 'SW Bend Backyard Landscaping',
    canonical: 'https://www.newportavelandscaping.com/portfolio/sw-bend-backyard',
    description: '',
  },
  '/portfolio/westside-outdoor-living': {
    title: 'Westside Outdoor Living Space',
    canonical: 'https://www.newportavelandscaping.com/portfolio/westside-outdoor-living',
    description: '',
  },
  '/resources/bend-turf-rebate-program': {
    title: 'Bend Turf Rebate Program | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/bend-turf-rebate-program',
    description: 'How to get rebates for converting your Bend lawn to xeriscape. The City of Bend\'s turf replacement program explained.',
  },
  '/resources/best-plants-xeriscape-central-oregon': {
    title: 'Best Plants for Xeriscaping in Central Oregon | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/best-plants-xeriscape-central-oregon',
    description: 'The best drought-tolerant plants for xeriscaping in Central Oregon. Native and adapted plants that thrive in Bend\'s high desert climate.',
  },
  '/resources/boulder-landscaping-cost-bend-oregon': {
    title: 'Boulder Landscaping Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/boulder-landscaping-cost-bend-oregon',
    description: 'What boulder and rock landscaping costs in Bend, Oregon. Delivery, placement, and design costs for Central Oregon properties.',
  },
  '/resources/central-oregon-landscaping-guide': {
    title: 'Central Oregon Landscaping Guide | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/central-oregon-landscaping-guide',
    description: 'Complete guide to landscaping in Central Oregon. Climate, plants, costs, and best practices for Bend, Redmond, Sisters, and surrounding areas.',
  },
  '/resources/commercial-landscaping-bend-oregon': {
    title: 'Commercial Landscaping in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/commercial-landscaping-bend-oregon',
    description: 'Commercial landscaping services in Bend, Oregon. Maintenance contracts, installation, and snow removal for businesses and HOAs.',
  },
  '/resources/drainage-solutions-cost-bend-oregon': {
    title: 'Drainage Solutions Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/drainage-solutions-cost-bend-oregon',
    description: 'What drainage solutions cost in Bend, Oregon. French drains, dry creek beds, and grading costs for Central Oregon properties.',
  },
  '/resources/drip-vs-spray-irrigation-bend-oregon': {
    title: 'Drip vs. Spray Irrigation in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/drip-vs-spray-irrigation-bend-oregon',
    description: 'Drip vs. spray irrigation for Bend, Oregon landscapes. Water efficiency, cost, and which system is right for your property.',
  },
  '/resources/driveway-paver-cost-bend-oregon': {
    title: 'Paver Driveway Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/driveway-paver-cost-bend-oregon',
    description: 'What a paver driveway costs in Bend, Oregon. Materials, installation, and how pavers compare to concrete and asphalt.',
  },
  '/resources/fall-landscaping-guide-bend-oregon': {
    title: 'Fall Landscaping Guide for Bend, Oregon | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/fall-landscaping-guide-bend-oregon',
    description: 'Complete fall landscaping checklist for Bend, Oregon. When to winterize sprinklers, aerate, overseed, and prepare your landscape for winter.',
  },
  '/resources/faq-irrigation-bend-oregon': {
    title: 'Sprinkler System FAQ — Bend, Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/faq-irrigation-bend-oregon',
    description: 'Answers to the most common questions about sprinkler system installation, repair, and winterization in Bend, Oregon.',
  },
  '/resources/faq-lawn-care-bend-oregon': {
    title: 'Lawn Care FAQ — Bend, Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/faq-lawn-care-bend-oregon',
    description: 'Common questions about lawn care, mowing, aeration, and fertilization in Bend, Oregon.',
  },
  '/resources/faq-outdoor-lighting-bend-oregon': {
    title: 'Outdoor Lighting FAQ — Bend, Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/faq-outdoor-lighting-bend-oregon',
    description: 'Common questions about landscape lighting installation in Bend, Oregon. Costs, LED vs. halogen, smart systems, and more.',
  },
  '/resources/faq-paver-patio-bend-oregon': {
    title: 'Paver Patio FAQ — Bend, Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/faq-paver-patio-bend-oregon',
    description: 'Answers to the most common questions about paver patio installation in Bend, Oregon. Costs, materials, timeline, warranty, and more.',
  },
  '/resources/faq-retaining-wall-bend-oregon': {
    title: 'Retaining Wall FAQ — Bend, Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/faq-retaining-wall-bend-oregon',
    description: 'Common questions about retaining wall installation in Bend, Oregon. Costs, materials, permits, and what to expect.',
  },
  '/resources/faq-snow-removal-bend-oregon': {
    title: 'Snow Removal FAQ — Bend, Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/faq-snow-removal-bend-oregon',
    description: 'Common questions about commercial and residential snow removal in Bend, Oregon. Pricing, contracts, and what to expect.',
  },
  '/resources/faq-water-feature-bend-oregon': {
    title: 'Water Feature FAQ — Bend, Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/faq-water-feature-bend-oregon',
    description: 'Common questions about water feature installation in Bend, Oregon. Ponds, fountains, waterfalls, and pondless features.',
  },
  '/resources/faq-xeriscape-bend-oregon': {
    title: 'Xeriscape FAQ — Bend, Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/faq-xeriscape-bend-oregon',
    description: 'Common questions about xeriscape landscaping in Bend, Oregon. Costs, plant selection, water savings, and the turf rebate program.',
  },
  '/resources/fencing-cost-bend-oregon': {
    title: 'Fencing Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/fencing-cost-bend-oregon',
    description: 'What fencing costs in Bend, Oregon. Wood, vinyl, and metal fence pricing for Central Oregon properties.',
  },
  '/resources/fire-pit-patio-cost-bend-oregon': {
    title: 'Fire Pit & Patio Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/fire-pit-patio-cost-bend-oregon',
    description: 'What a fire pit and patio costs in Bend, Oregon. Built-in vs. portable fire pits, patio combinations, and budgeting tips.',
  },
  '/resources/hoa-landscaping-bend-oregon': {
    title: 'HOA Landscaping in Bend, Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/hoa-landscaping-bend-oregon',
    description: 'HOA landscaping services in Bend, Oregon. Common area maintenance, seasonal color, and snow removal for Bend HOAs.',
  },
  '/resources/how-to-choose-landscaper-bend-oregon': {
    title: 'How to Choose a Landscaper in Bend, OR | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/how-to-choose-landscaper-bend-oregon',
    description: 'How to choose a landscaping company in Bend, Oregon. Questions to ask, red flags to avoid, and what to look for in a Central Oregon landscaper.',
  },
  '/resources/how-to-install-drip-irrigation-bend-oregon': {
    title: 'How to Install Drip Irrigation in Bend, OR | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/how-to-install-drip-irrigation-bend-oregon',
    description: 'Guide to drip irrigation installation in Bend, Oregon. DIY vs. professional installation, components, and tips for Central Oregon gardens.',
  },
  '/resources/how-to-maintain-paver-patio-bend-oregon': {
    title: 'How to Maintain a Paver Patio in Bend, OR | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/how-to-maintain-paver-patio-bend-oregon',
    description: 'How to maintain a paver patio in Bend, Oregon. Sealing, cleaning, weed prevention, and re-leveling tips for Central Oregon homeowners.',
  },
  '/resources/how-to-plant-trees-bend-oregon': {
    title: 'How to Plant Trees in Bend, Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/how-to-plant-trees-bend-oregon',
    description: 'How to plant trees in Bend, Oregon. Timing, hole preparation, watering, and the best trees for Central Oregon\'s high desert climate.',
  },
  '/resources/how-to-prevent-lawn-fungus-bend-oregon': {
    title: 'How to Prevent Lawn Fungus in Bend, Oregon | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/how-to-prevent-lawn-fungus-bend-oregon',
    description: 'How to prevent lawn fungus in Bend, Oregon. Watering habits, mowing practices, and treatment options for Central Oregon lawns.',
  },
  '/resources/how-to-read-landscape-proposal-bend-oregon': {
    title: 'How to Read a Landscape Proposal in Bend, OR | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/how-to-read-landscape-proposal-bend-oregon',
    description: 'How to evaluate a landscape proposal in Bend, Oregon. What to look for, red flags, and how to compare bids from Central Oregon landscapers.',
  },
  '/resources/how-to-select-pavers-bend-oregon': {
    title: 'How to Select Pavers for Your Bend, OR Patio | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/how-to-select-pavers-bend-oregon',
    description: 'How to choose the right pavers for your Bend, Oregon patio. Materials, colors, patterns, and what works best in Central Oregon\'s climate.',
  },
  '/resources/how-to-water-lawn-bend-oregon': {
    title: 'How to Water Your Lawn in Bend, Oregon | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/how-to-water-lawn-bend-oregon',
    description: 'Expert guide to watering your lawn in Bend, Oregon. How much water, when to water, and how to avoid common mistakes in Central Oregon\'s climate.',
  },
  '/resources/how-to-xeriscape-bend-oregon': {
    title: 'How to Xeriscape in Bend, Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/how-to-xeriscape-bend-oregon',
    description: 'Step-by-step guide to xeriscaping in Bend, Oregon. Planning, plant selection, irrigation, and what to expect from a xeriscape project.',
  },
  '/resources/irrigation-repair-bend-oregon': {
    title: 'Irrigation Repair Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/irrigation-repair-bend-oregon',
    description: 'What irrigation repair costs in Bend, Oregon. Common problems, diagnostic fees, and repair pricing for Central Oregon sprinkler systems.',
  },
  '/resources/landscape-design-cost-bend-oregon': {
    title: 'Landscape Design Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/landscape-design-cost-bend-oregon',
    description: 'What landscape design and installation costs in Bend, Oregon. Full-yard design, partial renovation, and what affects pricing in Central Oregon.',
  },
  '/resources/landscape-design-ideas-bend-oregon': {
    title: 'Landscape Design Ideas for Bend, Oregon | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/landscape-design-ideas-bend-oregon',
    description: 'Landscape design ideas for Bend, Oregon homes. Patio styles, plant combinations, and outdoor living concepts for Central Oregon.',
  },
  '/resources/landscape-lighting-bend-oregon': {
    title: 'Landscape Lighting Ideas for Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/landscape-lighting-bend-oregon',
    description: 'Landscape lighting ideas and design tips for Bend, Oregon homes. How to light your outdoor space for beauty and safety.',
  },
  '/resources/landscape-lighting-cost-bend-oregon': {
    title: 'Landscape Lighting Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/landscape-lighting-cost-bend-oregon',
    description: 'What landscape lighting installation costs in Bend, Oregon. Low-voltage LED systems, pathway lights, and uplighting pricing.',
  },
  '/resources/landscape-maintenance-plan-bend-oregon': {
    title: 'Landscape Maintenance Plans in Bend, OR | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/landscape-maintenance-plan-bend-oregon',
    description: 'Landscape maintenance plans for Bend, Oregon homeowners. What\'s included, pricing, and how to choose the right plan for your property.',
  },
  '/resources/landscape-transformation-bend-oregon': {
    title: 'Landscape Transformations in Bend, Oregon | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/landscape-transformation-bend-oregon',
    description: 'How Newport Avenue Landscaping transforms Bend, Oregon properties. Before and after examples and what\'s possible in Central Oregon.',
  },
  '/resources/landscape-warranty-bend-oregon': {
    title: 'Landscape Warranty in Bend, Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/landscape-warranty-bend-oregon',
    description: 'What landscape warranties cover in Bend, Oregon. Newport Avenue\'s 90-day plant warranty and 1-year irrigation warranty explained.',
  },
  '/resources/landscaping-bend-oregon': {
    title: 'Landscaping in Bend, Oregon: The Complete Guide | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/landscaping-bend-oregon',
    description: 'Everything you need to know about landscaping in Bend, Oregon. Climate, soil, services, costs, and how to find the right landscaper.',
  },
  '/resources/landscaping-company-bend-oregon': {
    title: 'Landscaping Companies in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/landscaping-company-bend-oregon',
    description: 'How to find and evaluate landscaping companies in Bend, Oregon. What to look for, questions to ask, and what sets great landscapers apart.',
  },
  '/resources/landscaping-cost-guide-bend-oregon': {
    title: 'Landscaping Cost Guide for Bend, Oregon | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/landscaping-cost-guide-bend-oregon',
    description: 'Complete landscaping cost guide for Bend, Oregon. All services priced — patios, irrigation, xeriscape, lawn care, and more.',
  },
  '/resources/landscaping-home-value-bend-oregon': {
    title: 'Does Landscaping Increase Home Value in Bend, OR? | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/landscaping-home-value-bend-oregon',
    description: 'How landscaping affects home value in Bend, Oregon. ROI on patios, xeriscape, irrigation, and lawn care in Central Oregon.',
  },
  '/resources/landscaping-seasons-bend-oregon': {
    title: 'Landscaping Seasons in Bend, Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/landscaping-seasons-bend-oregon',
    description: 'When to do what in your Bend, Oregon landscape. Month-by-month guide to landscaping tasks in Central Oregon.',
  },
  '/resources/landscaping-tips-bend-oregon': {
    title: 'Landscaping Tips for Bend, Oregon Homeowners | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/landscaping-tips-bend-oregon',
    description: 'Expert landscaping tips for Bend, Oregon homeowners. Practical advice for Central Oregon\'s high desert climate from 21+ years of experience.',
  },
  '/resources/lawn-maintenance-cost-bend-oregon': {
    title: 'Lawn Maintenance Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/lawn-maintenance-cost-bend-oregon',
    description: 'What lawn maintenance costs in Bend, Oregon. Mowing, aeration, fertilization, and full-service lawn care pricing for Central Oregon.',
  },
  '/resources/mulch-installation-cost-bend-oregon': {
    title: 'Mulch Installation Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/mulch-installation-cost-bend-oregon',
    description: 'What mulch installation costs in Bend, Oregon. Types of mulch, how much you need, and pricing for Central Oregon properties.',
  },
  '/resources/native-vs-adapted-plants-bend-oregon': {
    title: 'Native vs. Adapted Plants for Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/native-vs-adapted-plants-bend-oregon',
    description: 'Native vs. adapted plants for Bend, Oregon landscapes. Which plants thrive in Central Oregon\'s high desert climate?',
  },
  '/resources/new-construction-landscaping-bend-oregon': {
    title: 'New Construction Landscaping in Bend, OR | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/new-construction-landscaping-bend-oregon',
    description: 'Landscaping for new construction homes in Bend, Oregon. What to expect, timing, and costs for new home landscaping in Central Oregon.',
  },
  '/resources/outdoor-kitchen-cost-bend-oregon': {
    title: 'Outdoor Kitchen Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/outdoor-kitchen-cost-bend-oregon',
    description: 'What an outdoor kitchen costs in Bend, Oregon. Materials, appliances, installation, and budgeting tips for Central Oregon homeowners.',
  },
  '/resources/outdoor-lighting-cost-bend-oregon': {
    title: 'Outdoor Lighting Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/outdoor-lighting-cost-bend-oregon',
    description: 'What outdoor and landscape lighting costs in Bend, Oregon. LED systems, pathway lights, and installation pricing.',
  },
  '/resources/paver-patio-cost-bend-oregon': {
    title: 'Paver Patio Cost in Bend Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/paver-patio-cost-bend-oregon',
    description: 'Discover the cost of paver patios in Bend, Oregon. Get detailed insights on material, labor, and design expenses, plus tips for budgeting your project with Newport Ave Landscaping.',
  },
  '/resources/paver-walkway-cost-bend-oregon': {
    title: 'Paver Walkway Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/paver-walkway-cost-bend-oregon',
    description: 'What paver walkways cost in Bend, Oregon. Materials, installation, and what to expect from a professional walkway installation.',
  },
  '/resources/pavers-vs-concrete-bend-oregon': {
    title: 'Pavers vs. Concrete Patio in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/pavers-vs-concrete-bend-oregon',
    description: 'Pavers vs. poured concrete for patios in Bend, Oregon. Cost, durability, maintenance, and which is better for Central Oregon\'s climate.',
  },
  '/resources/perennial-garden-cost-bend-oregon': {
    title: 'Perennial Garden Installation Cost in Bend, OR | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/perennial-garden-cost-bend-oregon',
    description: 'What a perennial garden costs in Bend, Oregon. Plant selection, installation, and maintenance costs for Central Oregon gardens.',
  },
  '/resources/pergola-cost-bend-oregon': {
    title: 'Pergola Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/pergola-cost-bend-oregon',
    description: 'What a pergola costs in Bend, Oregon. Materials, installation, and design options for Central Oregon outdoor spaces.',
  },
  '/resources/professional-vs-diy-landscaping-bend-oregon': {
    title: 'Professional vs. DIY Landscaping in Bend, OR | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/professional-vs-diy-landscaping-bend-oregon',
    description: 'Professional vs. DIY landscaping in Bend, Oregon. When to hire a pro and when to do it yourself — an honest guide.',
  },
  '/resources/retaining-wall-cost-bend-oregon': {
    title: 'Retaining Wall Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/retaining-wall-cost-bend-oregon',
    description: 'What retaining walls cost in Bend, Oregon. Materials, installation, and what affects pricing for Central Oregon properties.',
  },
  '/resources/snow-removal-bend-oregon': {
    title: 'Snow Removal Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/snow-removal-bend-oregon',
    description: 'What snow removal costs in Bend, Oregon. Residential and commercial pricing, seasonal contracts, and what to expect.',
  },
  '/resources/sod-installation-cost-bend-oregon': {
    title: 'Sod Installation Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/sod-installation-cost-bend-oregon',
    description: 'What sod installation costs in Bend, Oregon. Pricing per square foot, site preparation, and what to expect from a new lawn installation.',
  },
  '/resources/sod-vs-seed-bend-oregon': {
    title: 'Sod vs. Seed for Lawns in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/sod-vs-seed-bend-oregon',
    description: 'Sod vs. seed for new lawns in Bend, Oregon. Cost, timeline, and which is better for Central Oregon\'s climate and soil.',
  },
  '/resources/spring-landscaping-guide-bend-oregon': {
    title: 'Spring Landscaping Guide for Bend, Oregon | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/spring-landscaping-guide-bend-oregon',
    description: 'Complete spring landscaping checklist for Bend, Oregon homeowners. When to aerate, activate sprinklers, plant, and clean up your yard.',
  },
  '/resources/sprinkler-system-cost-bend-oregon': {
    title: 'Sprinkler System Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/sprinkler-system-cost-bend-oregon',
    description: 'What a sprinkler system costs in Bend, Oregon. New installation, repair, and winterization pricing for Central Oregon.',
  },
  '/resources/sprinkler-winterization-guide-bend-oregon': {
    title: 'Sprinkler Winterization Guide for Bend, OR | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/sprinkler-winterization-guide-bend-oregon',
    description: 'How to winterize your sprinkler system in Bend, Oregon. Step-by-step guide to protecting your irrigation system from freeze damage.',
  },
  '/resources/summer-landscaping-guide-bend-oregon': {
    title: 'Summer Landscaping Guide for Bend, Oregon | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/summer-landscaping-guide-bend-oregon',
    description: 'How to keep your Bend landscape healthy through the hot, dry Central Oregon summer. Watering, mowing, and heat stress tips.',
  },
  '/resources/tree-removal-cost-bend-oregon': {
    title: 'Tree Removal Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/tree-removal-cost-bend-oregon',
    description: 'What tree removal costs in Bend, Oregon. Pricing by tree size, stump grinding, and what affects the total cost.',
  },
  '/resources/understanding-soil-bend-oregon': {
    title: 'Understanding Soil in Bend, Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/understanding-soil-bend-oregon',
    description: 'What you need to know about soil in Bend, Oregon. Volcanic soil, pH, amendments, and how to grow a healthy landscape in Central Oregon.',
  },
  '/resources/water-feature-cost-bend-oregon': {
    title: 'Water Feature Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/water-feature-cost-bend-oregon',
    description: 'What water features cost in Bend, Oregon. Pondless waterfalls, koi ponds, fountains, and installation pricing for Central Oregon.',
  },
  '/resources/when-to-aerate-lawn-bend-oregon': {
    title: 'When to Aerate Your Lawn in Bend, Oregon | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/when-to-aerate-lawn-bend-oregon',
    description: 'Best timing for lawn aeration in Bend, Oregon. Spring vs. fall aeration, how often to aerate, and what to expect in Central Oregon.',
  },
  '/resources/winter-landscaping-guide-bend-oregon': {
    title: 'Winter Landscaping Guide for Bend, Oregon | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/winter-landscaping-guide-bend-oregon',
    description: 'What to do with your Bend landscape in winter. Snow removal, protecting plants, and planning for spring.',
  },
  '/resources/xeriscape-cost-bend-oregon': {
    title: 'Xeriscape Cost in Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/resources/xeriscape-cost-bend-oregon',
    description: 'What xeriscape landscaping costs in Bend, Oregon. Full cost breakdown for water-wise landscaping in Central Oregon.',
  },
  '/resources/xeriscape-vs-traditional-lawn-bend-oregon': {
    title: 'Xeriscape vs. Traditional Lawn in Bend, OR | Newport Ave',
    canonical: 'https://www.newportavelandscaping.com/resources/xeriscape-vs-traditional-lawn-bend-oregon',
    description: 'Xeriscape vs. traditional lawn in Bend, Oregon. Water use, cost, maintenance, and which is right for your Central Oregon property.',
  },
  '/service-areas': {
    title: 'Newport Avenue Landscaping Service Area — Central Oregon',
    canonical: 'https://www.newportavelandscaping.com/service-areas',
    description: 'Newport Avenue Landscaping serves Bend, Redmond, Sisters, Sunriver, La Pine, Tumalo, Prineville, and Madras. Paver patios, xeriscape, irrigation, lawn care, and landscape design across Central Oregon.',
  },
  '/service-areas/alfalfa-irrigation': {
    title: 'Irrigation Installation & Repair in Alfalfa, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/alfalfa-irrigation',
    description: 'Professional irrigation installation & repair in Alfalfa, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/alfalfa-lawn-care': {
    title: 'Lawn Care & Maintenance in Alfalfa, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/alfalfa-lawn-care',
    description: 'Professional lawn care & maintenance in Alfalfa, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/alfalfa-paver-patio': {
    title: 'Paver Patio Installation in Alfalfa, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/alfalfa-paver-patio',
    description: 'Professional paver patio installation in Alfalfa, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/awbrey-butte-landscaping': {
    title: 'Awbrey Butte Landscaping — Bend, Oregon | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/awbrey-butte-landscaping',
    description: 'Expert landscaping for Awbrey Butte homes in Bend, OR. Hillside design, fire-wise solutions, HOA compliance, drought-tolerant plantings, and irrigation. LCB #9153. Free consultation.',
  },
  '/service-areas/bend-country-club-landscaping': {
    title: 'Landscaping in Bend Country Club, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/bend-country-club-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Bend Country Club, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/bend-east-side-landscaping': {
    title: 'Landscaping in Bend East Side, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/bend-east-side-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Bend East Side, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/bend-south-landscaping': {
    title: 'Landscaping in Bend South, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/bend-south-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Bend South, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/bend-westside-landscaping': {
    title: 'Landscaping in Bend\'s Westside, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/bend-westside-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Bend\'s Westside, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/broken-top-landscaping': {
    title: 'Broken Top Landscaping — Bend, Oregon | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/broken-top-landscaping',
    description: 'Luxury landscaping for Broken Top homes in Bend, OR. Estate design, water features, outdoor living, HOA compliance, and year-round maintenance inside Bend\'s premier gated community. LCB #9153.',
  },
  '/service-areas/century-drive-corridor-landscaping': {
    title: 'Landscaping in Century Drive Corridor, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/century-drive-corridor-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Century Drive Corridor, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/crooked-river-ranch': {
    title: 'Landscaping in Crooked River Ranch, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/crooked-river-ranch',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Crooked River Ranch, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/crooked-river-ranch-irrigation': {
    title: 'Irrigation Installation & Repair in Crooked River Ranch, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/crooked-river-ranch-irrigation',
    description: 'Professional irrigation installation & repair in Crooked River Ranch, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/crooked-river-ranch-lawn-care': {
    title: 'Lawn Care & Maintenance in Crooked River Ranch, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/crooked-river-ranch-lawn-care',
    description: 'Professional lawn care & maintenance in Crooked River Ranch, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/crooked-river-ranch-paver-patio': {
    title: 'Paver Patio Installation in Crooked River Ranch, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/crooked-river-ranch-paver-patio',
    description: 'Professional paver patio installation in Crooked River Ranch, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/culver': {
    title: 'Landscaping in Culver, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/culver',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Culver, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/culver-irrigation': {
    title: 'Irrigation Installation & Repair in Culver, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/culver-irrigation',
    description: 'Professional irrigation installation & repair in Culver, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/culver-lawn-care': {
    title: 'Lawn Care & Maintenance in Culver, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/culver-lawn-care',
    description: 'Professional lawn care & maintenance in Culver, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/culver-paver-patio': {
    title: 'Paver Patio Installation in Culver, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/culver-paver-patio',
    description: 'Professional paver patio installation in Culver, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/deschutes-river-woods-landscaping': {
    title: 'Landscaping in Deschutes River Woods, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/deschutes-river-woods-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Deschutes River Woods, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/discovery-west-landscaping': {
    title: 'Landscaping Discovery West Bend Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/discovery-west-landscaping',
    description: 'Discover expert landscaping services in Discovery West, Bend Oregon. Newport Ave Landscaping specializes in modern, xeriscape-friendly designs for homes and HOAs.',
  },
  '/service-areas/eagle-crest-landscaping': {
    title: 'Eagle Crest Landscaping & Irrigation | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/eagle-crest-landscaping',
    description: 'Expert landscaping and irrigation for Eagle Crest Resort homeowners in Redmond, Oregon. Drought-tolerant design, HOA compliance, fire-wise landscaping, and vacation property maintenance. LCB #9153.',
  },
  '/service-areas/hunnell-road-area-landscaping': {
    title: 'Landscaping in Hunnell Road Area, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/hunnell-road-area-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Hunnell Road Area, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/la-pine': {
    title: 'Landscaping in La Pine, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/la-pine',
    description: 'Professional landscaping, paver patios, irrigation, xeriscape, and lawn care in La Pine, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/la-pine-landscape-design': {
    title: 'Landscape Design & Installation in La Pine, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/la-pine-landscape-design',
    description: 'Professional landscape design & installation in La Pine, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/la-pine-lawn-care': {
    title: 'Lawn Care & Maintenance in La Pine, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/la-pine-lawn-care',
    description: 'Professional lawn care & maintenance in La Pine, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/la-pine-paver-patio': {
    title: 'Paver Patio Installation in La Pine, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/la-pine-paver-patio',
    description: 'Professional paver patio installation in La Pine, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/la-pine-sprinkler-system': {
    title: 'Sprinkler System Installation in La Pine, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/la-pine-sprinkler-system',
    description: 'Professional sprinkler system installation in La Pine, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/la-pine-xeriscape': {
    title: 'Xeriscape Landscaping in La Pine, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/la-pine-xeriscape',
    description: 'Professional xeriscape landscaping in La Pine, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/larkspur-landscaping': {
    title: 'Landscaping in Larkspur, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/larkspur-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Larkspur, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/lava-butte-area-landscaping': {
    title: 'Landscaping in Lava Butte Area, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/lava-butte-area-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Lava Butte Area, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/madras': {
    title: 'Landscaping in Madras, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/madras',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Madras, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/madras-irrigation': {
    title: 'Irrigation Installation & Repair in Madras, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/madras-irrigation',
    description: 'Professional irrigation installation & repair in Madras, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/madras-lawn-care': {
    title: 'Lawn Care & Maintenance in Madras, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/madras-lawn-care',
    description: 'Professional lawn care & maintenance in Madras, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/madras-paver-patio': {
    title: 'Paver Patio Installation in Madras, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/madras-paver-patio',
    description: 'Professional paver patio installation in Madras, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/murphy-road-area-landscaping': {
    title: 'Landscaping in Murphy Road Area, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/murphy-road-area-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Murphy Road Area, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/northeast-bend-landscaping': {
    title: 'Landscaping in Northeast Bend, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/northeast-bend-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Northeast Bend, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/northwest-crossing-landscaping': {
    title: 'NorthWest Crossing Landscaping — Bend, Oregon | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/northwest-crossing-landscaping',
    description: 'Expert landscaping for NorthWest Crossing homes in Bend, OR. ARC approval assistance, HOA-compliant designs, drought-tolerant plantings, and irrigation. LCB #9153. Free consultation.',
  },
  '/service-areas/old-mill-district-landscaping': {
    title: 'Landscaping in Old Mill District, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/old-mill-district-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Old Mill District, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/orion-greens-landscaping': {
    title: 'Landscaping in Orion Greens, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/orion-greens-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Orion Greens, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/powell-butte-irrigation': {
    title: 'Irrigation Installation & Repair in Powell Butte, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/powell-butte-irrigation',
    description: 'Professional irrigation installation & repair in Powell Butte, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/powell-butte-landscaping': {
    title: 'Powell Butte Landscaping & Irrigation | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/powell-butte-landscaping',
    description: 'Expert landscaping and irrigation for Powell Butte, Oregon acreage properties. Drought-tolerant design, large-lot irrigation, retaining walls, and seasonal maintenance. LCB #9153. Free consultation.',
  },
  '/service-areas/powell-butte-lawn-care': {
    title: 'Lawn Care & Maintenance in Powell Butte, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/powell-butte-lawn-care',
    description: 'Professional lawn care & maintenance in Powell Butte, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/powell-butte-paver-patio': {
    title: 'Paver Patio Installation in Powell Butte, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/powell-butte-paver-patio',
    description: 'Professional paver patio installation in Powell Butte, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/prineville': {
    title: 'Landscaping in Prineville, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/prineville',
    description: 'Professional landscaping, paver patios, irrigation, xeriscape, and lawn care in Prineville, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/prineville-landscape-design': {
    title: 'Landscape Design & Installation in Prineville, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/prineville-landscape-design',
    description: 'Professional landscape design & installation in Prineville, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/prineville-lawn-care': {
    title: 'Lawn Care & Maintenance in Prineville, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/prineville-lawn-care',
    description: 'Professional lawn care & maintenance in Prineville, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/prineville-paver-patio': {
    title: 'Paver Patio Installation in Prineville, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/prineville-paver-patio',
    description: 'Professional paver patio installation in Prineville, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/prineville-sprinkler-system': {
    title: 'Sprinkler System Installation in Prineville, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/prineville-sprinkler-system',
    description: 'Professional sprinkler system installation in Prineville, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/prineville-xeriscape': {
    title: 'Xeriscape Landscaping in Prineville, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/prineville-xeriscape',
    description: 'Professional xeriscape landscaping in Prineville, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/redmond': {
    title: 'Landscaping in Redmond, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/redmond',
    description: 'Professional landscaping, paver patios, irrigation, xeriscape, and lawn care in Redmond, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/redmond-landscape-design': {
    title: 'Landscape Design & Installation in Redmond, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/redmond-landscape-design',
    description: 'Professional landscape design & installation in Redmond, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/redmond-landscaping': {
    title: 'Landscaping Redmond Oregon | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/redmond-landscaping',
    description: 'Newport Ave Landscaping offers expert landscaping services in Redmond, Oregon. Specializing in new construction, commercial properties, and adapting to Redmond\'s unique climate and soils. Licensed & Bonded, LCB #9153.',
  },
  '/service-areas/redmond-lawn-care': {
    title: 'Lawn Care & Maintenance in Redmond, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/redmond-lawn-care',
    description: 'Professional lawn care & maintenance in Redmond, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/redmond-paver-patio': {
    title: 'Paver Patio Installation in Redmond, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/redmond-paver-patio',
    description: 'Professional paver patio installation in Redmond, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/redmond-sprinkler-system': {
    title: 'Sprinkler System Installation in Redmond, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/redmond-sprinkler-system',
    description: 'Professional sprinkler system installation in Redmond, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/redmond-xeriscape': {
    title: 'Xeriscape Landscaping in Redmond, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/redmond-xeriscape',
    description: 'Professional xeriscape landscaping in Redmond, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/river-west-landscaping': {
    title: 'Landscaping in River West, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/river-west-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in River West, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/shevlin-meadows-landscaping': {
    title: 'Landscaping in Shevlin Meadows, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/shevlin-meadows-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Shevlin Meadows, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/shevlin-park-area-landscaping': {
    title: 'Landscaping in Shevlin Park Area, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/shevlin-park-area-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Shevlin Park Area, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/sisters': {
    title: 'Landscaping in Sisters, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/sisters',
    description: 'Professional landscaping, paver patios, irrigation, xeriscape, and lawn care in Sisters, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/sisters-landscape-design': {
    title: 'Landscape Design & Installation in Sisters, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/sisters-landscape-design',
    description: 'Professional landscape design & installation in Sisters, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/sisters-lawn-care': {
    title: 'Lawn Care & Maintenance in Sisters, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/sisters-lawn-care',
    description: 'Professional lawn care & maintenance in Sisters, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/sisters-paver-patio': {
    title: 'Paver Patio Installation in Sisters, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/sisters-paver-patio',
    description: 'Professional paver patio installation in Sisters, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/sisters-sprinkler-system': {
    title: 'Sprinkler System Installation in Sisters, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/sisters-sprinkler-system',
    description: 'Professional sprinkler system installation in Sisters, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/sisters-xeriscape': {
    title: 'Xeriscape Landscaping in Sisters, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/sisters-xeriscape',
    description: 'Professional xeriscape landscaping in Sisters, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/skyline-ranch-landscaping': {
    title: 'Landscaping in Skyline Ranch, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/skyline-ranch-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Skyline Ranch, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/southeast-bend-landscaping': {
    title: 'Landscaping in Southeast Bend, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/southeast-bend-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Southeast Bend, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/summit-west-landscaping': {
    title: 'Landscaping in Summit West, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/summit-west-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Summit West, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/sunriver': {
    title: 'Landscaping in Sunriver, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/sunriver',
    description: 'Professional landscaping, paver patios, irrigation, xeriscape, and lawn care in Sunriver, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/sunriver-landscape-design': {
    title: 'Landscape Design & Installation in Sunriver, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/sunriver-landscape-design',
    description: 'Professional landscape design & installation in Sunriver, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/sunriver-landscaping': {
    title: 'Landscaping Sunriver Oregon: Expert Services for High Desert Homes | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/sunriver-landscaping',
    description: 'Discover expert landscaping services in Sunriver, Oregon. Newport Ave Landscaping specializes in SROA compliance, vacation rental maintenance, pine needle cleanup, and high desert plant palettes. Licensed & Bonded, LCB #9153.',
  },
  '/service-areas/sunriver-lawn-care': {
    title: 'Lawn Care & Maintenance in Sunriver, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/sunriver-lawn-care',
    description: 'Professional lawn care & maintenance in Sunriver, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/sunriver-paver-patio': {
    title: 'Paver Patio Installation in Sunriver, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/sunriver-paver-patio',
    description: 'Professional paver patio installation in Sunriver, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/sunriver-sprinkler-system': {
    title: 'Sprinkler System Installation in Sunriver, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/sunriver-sprinkler-system',
    description: 'Professional sprinkler system installation in Sunriver, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/sunriver-xeriscape': {
    title: 'Xeriscape Landscaping in Sunriver, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/sunriver-xeriscape',
    description: 'Professional xeriscape landscaping in Sunriver, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/terrebonne': {
    title: 'Landscaping in Terrebonne, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/terrebonne',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Terrebonne, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/service-areas/terrebonne-irrigation': {
    title: 'Irrigation Installation & Repair in Terrebonne, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/terrebonne-irrigation',
    description: 'Professional irrigation installation & repair in Terrebonne, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/terrebonne-lawn-care': {
    title: 'Lawn Care & Maintenance in Terrebonne, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/terrebonne-lawn-care',
    description: 'Professional lawn care & maintenance in Terrebonne, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/terrebonne-paver-patio': {
    title: 'Paver Patio Installation in Terrebonne, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/terrebonne-paver-patio',
    description: 'Professional paver patio installation in Terrebonne, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/tumalo-landscape-design': {
    title: 'Landscape Design & Installation in Tumalo, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/tumalo-landscape-design',
    description: 'Professional landscape design & installation in Tumalo, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/tumalo-lawn-care': {
    title: 'Lawn Care & Maintenance in Tumalo, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/tumalo-lawn-care',
    description: 'Professional lawn care & maintenance in Tumalo, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/tumalo-paver-patio': {
    title: 'Paver Patio Installation in Tumalo, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/tumalo-paver-patio',
    description: 'Professional paver patio installation in Tumalo, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/tumalo-sprinkler-system': {
    title: 'Sprinkler System Installation in Tumalo, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/tumalo-sprinkler-system',
    description: 'Professional sprinkler system installation in Tumalo, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/tumalo-xeriscape': {
    title: 'Xeriscape Landscaping in Tumalo, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/tumalo-xeriscape',
    description: 'Professional xeriscape landscaping in Tumalo, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years serving Central Oregon. Free consultations.',
  },
  '/service-areas/woodriver-village-landscaping': {
    title: 'Landscaping in Woodriver Village, Bend, OR | Newport Ave Landscaping',
    canonical: 'https://www.newportavelandscaping.com/service-areas/woodriver-village-landscaping',
    description: 'Professional landscaping, paver patios, irrigation, and lawn care in Woodriver Village, Bend, Oregon. Newport Avenue Landscaping — licensed, bonded, 21+ years. Free consultations.',
  },
  '/services': {
    title: 'Landscaping Services Bend Oregon | Design, Install & Maintenance',
    canonical: 'https://www.newportavelandscaping.com/services',
    description: 'Full-service landscaping in Bend, OR: custom design & build, pavers, irrigation, xeriscaping, water features, outdoor living, lighting & snow removal. LCB #9153. Free estimates.',
  },
  '/services/aeration': {
    title: 'Lawn Aeration Bend Oregon | Core Aeration & Overseeding | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/aeration',
    description: 'Professional lawn aeration and overseeding in Bend, Oregon. Relieve soil compaction, improve water penetration, and thicken your turf. From $97/service. LCB #9153.',
  },
  '/services/commercial-maintenance': {
    title: 'Commercial Landscaping Bend Oregon | HOA & Office Park Maintenance | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/commercial-maintenance',
    description: 'Commercial landscape maintenance for HOAs, office parks, and retail properties in Bend, Oregon. Weekly service, seasonal cleanups, and irrigation management. LCB #9153.',
  },
  '/services/decks': {
    title: 'Deck Builder Bend Oregon | Composite & Wood Decks | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/services/decks',
    description: 'Custom deck building and pergola installation in Bend, Oregon. Composite, Trex, cedar, and pressure-treated decks. Licensed deck contractor LCB #9153. Free estimates.',
  },
  '/services/drainage': {
    title: 'Drainage Solutions Bend Oregon | French Drains, Dry Creek Beds & Grading | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/drainage',
    description: 'Drainage installation and correction in Bend, Oregon. French drains, dry creek beds, catch basins, and grading correction. Free site assessments. LCB #9153.',
  },
  '/services/fire-features': {
    title: 'Fire Pit Installation Bend Oregon | Custom Fire Pits & Outdoor Fireplaces | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/fire-features',
    description: 'Custom fire pit and outdoor fireplace installation in Bend, Oregon. Natural gas, propane, and wood-burning options. Design and build by Newport Avenue Landscaping. LCB #9153.',
  },
  '/services/firewise-landscaping': {
    title: 'Firewise Landscaping Bend Oregon | Defensible Space Contractor | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/firewise-landscaping',
    description: 'Firewise landscaping and defensible space services in Bend, Oregon. Juniper removal, fire-resistant replanting, and zone-based vegetation management for Deschutes County homeowners. Free assessment. LCB #9153.',
  },
  '/services/irrigation': {
    title: 'Sprinkler System Installation Bend Oregon | Irrigation Design & Install | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/irrigation',
    description: 'Professional irrigation system design and installation in Bend, Oregon. Smart controllers, drip irrigation, and full lawn sprinkler systems. $1,600–$2,000/zone. LCB #9153.',
  },
  '/services/landscape-design': {
    title: 'Landscape Design Bend Oregon | Custom Landscape Design & Installation | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/landscape-design',
    description: 'Custom landscape design and installation in Bend, Oregon. Full-service design for residential and commercial properties in Central Oregon. Free consultations. LCB #9153.',
  },
  '/services/landscape-lighting': {
    title: 'Landscape Lighting Bend Oregon | Outdoor LED Lighting Design & Install | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/landscape-lighting',
    description: 'Professional landscape lighting design and installation in Bend, Oregon. LED path lights, uplighting, and outdoor living illumination. Transform your property after dark. LCB #9153.',
  },
  '/services/lawn-fungus': {
    title: 'Lawn Fungus Treatment Bend Oregon | Dollar Spot, Brown Patch & Turf Disease | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/lawn-fungus',
    description: 'Lawn fungus diagnosis and treatment in Bend, Oregon. Dollar spot, brown patch, rust, and other turf diseases. Expert diagnosis and targeted treatment. LCB #9153.',
  },
  '/services/lawn-service': {
    title: 'Lawn Care Bend Oregon | Weekly Lawn Mowing & Maintenance Service | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/lawn-service',
    description: 'Weekly lawn mowing, edging, and maintenance in Bend, Oregon. From $97/service. Fertilization, weed control, and seasonal cleanups. Serving Bend since 2010. LCB #9153.',
  },
  '/services/outdoor-living': {
    title: 'Outdoor Kitchen Bend Oregon | Outdoor Living Spaces & Covered Patios | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/outdoor-living',
    description: 'Custom outdoor kitchens, living spaces, and covered patios in Bend, Oregon. Design and installation by Newport Avenue Landscaping. Free consultations. LCB #9153.',
  },
  '/services/pavers': {
    title: 'Paver Patio Bend Oregon | Paver Installation & Walkways | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/services/pavers',
    description: 'Custom paver patio and walkway installation in Bend, Oregon. Natural stone, concrete pavers, and retaining walls. 90-day plant warranty, 1-year irrigation warranty. LCB #9153.',
  },
  '/services/retaining-walls': {
    title: 'Retaining Wall Installation Bend Oregon | Basalt Boulder & Block Walls | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/retaining-walls',
    description: 'Retaining wall design and installation in Bend, Oregon. Basalt boulder, concrete block, and natural stone walls. Engineered for Central Oregon\'s freeze-thaw climate. Free estimates. LCB #9153.',
  },
  '/services/snow-removal': {
    title: 'Snow Removal Bend Oregon | Residential & Commercial Snow Plowing | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/snow-removal',
    description: 'Residential and commercial snow removal in Bend, Oregon. Driveway plowing, walkway clearing, and de-icing. Seasonal contracts and on-call service. LCB #9153.',
  },
  '/services/sprinkler-activation': {
    title: 'Sprinkler Activation Bend Oregon | Spring Sprinkler Startup Service | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/sprinkler-activation',
    description: 'Spring sprinkler system startup and activation in Bend, Oregon. Zone checks, head adjustments, and controller programming. $140/tech hour. Schedule now. LCB #9153.',
  },
  '/services/sprinkler-blowout': {
    title: 'Sprinkler Blowout Bend Oregon | Winterization Service | Newport Avenue Landscaping',
    canonical: 'https://www.newportavelandscaping.com/services/sprinkler-blowout',
    description: 'Professional sprinkler blowout and winterization in Bend, Oregon. $140/tech hour. Protect your irrigation system before the first freeze. Schedule early. LCB #9153.',
  },
  '/services/sprinkler-repair': {
    title: 'Sprinkler Repair Bend Oregon | Irrigation Repair & Troubleshooting | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/sprinkler-repair',
    description: 'Expert sprinkler repair and troubleshooting in Bend, Oregon. $140/tech hour. Broken heads, valve failures, controller issues, and backflow testing. Same-week scheduling. LCB #9153.',
  },
  '/services/water-features': {
    title: 'Water Features Bend Oregon | Ponds, Waterfalls & Koi Ponds | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/water-features',
    description: 'Custom ponds, waterfalls, and water features in Bend, Oregon. Design, installation, and maintenance by Newport Avenue Landscaping. Transform your outdoor space. LCB #9153.',
  },
  '/services/water-wise-landscaping': {
    title: 'Water-Wise Landscaping Bend Oregon | Xeriscape & Turf Replacement | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/water-wise-landscaping',
    description: 'Expert water-wise landscaping in Bend, OR. Xeriscape conversions, drip irrigation, smart controllers, and City of Bend Turf Replacement Rebate assistance. LCB #9153. Call (541) 617-8873.',
  },
  '/services/xeriscaping': {
    title: 'Xeriscape Landscaping Bend Oregon | Water-Wise & Drought-Tolerant Design | Newport Avenue',
    canonical: 'https://www.newportavelandscaping.com/services/xeriscaping',
    description: 'Water-wise xeriscape landscaping in Bend, Oregon. Drought-tolerant plants, decorative rock, and low-maintenance designs for Central Oregon\'s climate. LCB #9153.',
  },
};

export const defaultMeta: RouteMeta = {
  title: 'Newport Avenue Landscaping | Bend, Oregon',
  canonical: 'https://www.newportavelandscaping.com/',
  description: "Central Oregon's premier landscaping company since 2005. Custom landscape design, installation, maintenance & irrigation in Bend, Redmond, Sisters & beyond.",
};
