import CityPageLayout from "@/components/CityPageLayout";

export default function BendPage() {
  return (
    <CityPageLayout
      city="Bend"
      region="Central Oregon"
      heroImage="/manus-storage/NewportAveLandcaping-9_97b731b0_1204d3ca.webp"
      heroPosition="center 40%"
      tagline="Transforming Bend's High-Desert Landscapes into Stunning Outdoor Sanctuaries"
      seoTitle="Bend Landscaping Oregon & Bend Lawn Care | Newport Avenue Landscaping"
      seoDescription="Newport Avenue Landscaping offers premier landscaping and lawn care services in Bend, Oregon. With LCB #9153, we provide free estimates for all your outdoor needs."
      canonicalPath="/landscaping/bend"
      intro="Newport Avenue Landscaping has proudly served the vibrant community of Bend, Oregon, for over 21 years, establishing deep roots in its unique high-desert landscape. We understand the distinct character of neighborhoods like Awbrey Butte, NorthWest Crossing, Broken Top, Discovery West, and River West -- crafting outdoor spaces that seamlessly blend with Bend's natural beauty and the adventurous spirit of Central Oregon. Our team brings unparalleled expertise to every project, from a simple lawn care program to a complete design-build transformation with retaining walls, water features, and outdoor living spaces. We are dedicated to transforming your vision into a stunning, lasting reality. Every project we take on in Bend is backed by our 90-day plant warranty and 1-year irrigation warranty and performed entirely by our own licensed crew -- we never use subcontractors. Whether you live on the west side's volcanic rimrock terrain or in a newer east-side development, we know how to make your property thrive in Bend's demanding climate."
      communityNote="Bend's high-desert climate -- USDA Zone 6a, 300+ days of sunshine, hot dry summers, and cold winters with hard freezes -- presents unique landscaping opportunities and challenges that require genuine local expertise. The volcanic pumice soil, while exceptionally well-draining, is low in organic matter and requires targeted soil amendment to support diverse plant life. With only 11 inches of annual precipitation, water-wise landscaping is not just a trend here -- it is a necessity. Efficient drip irrigation, drought-tolerant native plantings, and thoughtful xeriscape design are the foundation of every sustainable Bend landscape. Bend's rapid growth has also brought new neighborhoods with varying soil profiles and sun exposures: the elevated west-side lots of Awbrey Butte face different challenges than the flatter terrain of NorthWest Crossing or the juniper-studded parcels near Tumalo Road. Our designers account for all of these variables -- elevation, slope, soil composition, HOA guidelines, and your personal aesthetic -- to deliver landscapes that look great on day one and continue to improve over time. From spring green-up through fall color and winter snow management, Newport Avenue is Bend's full-service outdoor partner."
      services={[
        { icon: "maintenance", name: "Bend Lawn Care & Maintenance", description: "Our comprehensive lawn care services in Bend ensure your turf remains lush and healthy through all seasons. We provide expert mowing, fertilization, aeration, overseeding, and pest control tailored to Bend's unique climate and volcanic pumice soil conditions. Our maintenance crews are on a consistent schedule -- your lawn is never forgotten or skipped. We service residential and commercial properties across all Bend neighborhoods.", href: "/services/lawn-service" },
        { icon: "sprinklers", name: "Bend Irrigation System Installation & Repair", description: "Efficient irrigation is essential in Bend's dry climate. We design, install, and repair smart irrigation systems -- from drip systems for xeriscape beds to full rotor-and-spray systems for traditional lawns. We also perform annual sprinkler activations in spring and blowouts in fall to protect your system from freeze damage. Our irrigation team handles everything from new installs to troubleshooting and head replacement.", href: "/services/irrigation" },
        { icon: "design", name: "Bend Landscape Design & Installation", description: "Our design-build process starts with a free site visit and ends with a landscape that exceeds your expectations. We create CAD-based design plans, 3D renderings for larger projects, and detailed plant and material specifications. Our installation crews are experienced with Bend's terrain -- from basalt boulder retaining walls on steep west-side lots to native plant installations in fire-wise zones near the urban-wildland interface.", href: "/services/landscape-design" },
        { icon: "outdoor", name: "Bend Outdoor Living Spaces & Hardscaping", description: "Bend's outdoor culture demands exceptional outdoor living spaces. We build custom paver patios, outdoor kitchens, fire pits, covered pergolas, and seating walls that extend your livable square footage into the beautiful Central Oregon outdoors. Our most complex outdoor living build to date exceeded $150,000 -- and we bring that same attention to detail to projects of every scale.", href: "/services/outdoor-living" },
        { icon: "architecture", name: "Bend Xeriscaping & Drought-Tolerant Landscaping", description: "Embrace Bend's high-desert environment with stunning and sustainable xeriscape designs that conserve water without sacrificing beauty. We specialize in selecting drought-tolerant plants, efficient drip irrigation, and decorative rock and boulder work to create low-maintenance, eco-friendly landscapes. Our xeriscape designs thrive in Bend's arid conditions, reduce water bills, and often qualify for City of Bend water conservation rebates.", href: "/services/xeriscaping" },
        { icon: "commercial", name: "Bend Commercial Landscaping & Snow Removal", description: "Newport Avenue Landscaping provides reliable commercial landscaping services for businesses, HOAs, and multi-family properties across Bend. During winter, our efficient snow removal and de-icing services keep your commercial property safe and accessible. We are your trusted partner for year-round commercial property maintenance in Bend, with the crew size and equipment to handle large-scale accounts.", href: "/services/snow-removal" },
      ]}
      whyUs={[
        "Over 21 years of dedicated service to the Bend community, building a reputation for excellence and reliability.",
        "Fully licensed, bonded, and insured with Oregon LCB #9153, ensuring peace of mind for every project.",
        "A robust team of 150+ in-house landscaping professionals -- we never use subcontractors.",
        "Deep local knowledge of Bend's unique climate, volcanic soil, and plant life, enabling us to create thriving landscapes.",
        "90-day plant warranty and 1-year irrigation warranty on all installation projects -- one of the strongest in the industry.",
        "Free, no-obligation estimates with a prompt site visit and detailed written proposal within 24–48 hours."
      ]}
      nearbyAreas={[
        { label: "Tumalo", href: "/landscaping/tumalo" },
        { label: "Redmond", href: "/landscaping/redmond" },
        { label: "Sisters", href: "/landscaping/sisters" },
        { label: "Sunriver", href: "/landscaping/sunriver" },
        { label: "Powell Butte", href: "/landscaping/powell-butte" },
        { label: "Awbrey Butte", href: "/landscaping/awbrey-butte" },
        { label: "NorthWest Crossing", href: "/landscaping/northwest-crossing" },
        { label: "Broken Top", href: "/landscaping/broken-top" }
      ]}
      ctaNote="Ready to enhance your Bend property's curb appeal and functionality? Contact Newport Avenue Landscaping today for a free, no-obligation estimate. We pride ourselves on prompt response times and personalized site visits to discuss your specific needs. Ask about our seasonal landscaping programs designed to keep your Bend landscape vibrant and healthy throughout the year."
      faqs={[
        { question: "How much does landscaping cost in Bend, Oregon?", answer: "Landscaping costs in Bend vary widely based on project scope and materials. For basic lawn care services, residents can expect to pay from $97 per service. Larger projects like comprehensive cleanups typically start around $600. Irrigation system installations can range from $1,600 to $2,000 per zone, depending on complexity. Full landscape design and installation projects, including hardscaping and planting, can range from $15,000 to $80,000+, reflecting the bespoke nature of Bend's high-end properties. We provide detailed written estimates after a free site visit so you know exactly what to expect." },
        { question: "What landscaping services does Newport Avenue offer in Bend?", answer: "Newport Avenue Landscaping offers a full spectrum of services tailored for Bend's unique environment. This includes expert lawn care and maintenance, advanced irrigation system design and repair, custom landscape design and installation, and the creation of stunning outdoor living spaces with hardscaping. We also specialize in water-wise xeriscaping, retaining walls and boulder work, landscape lighting, fire features, water features, and provide essential commercial landscaping and snow removal services to keep Bend businesses looking their best year-round." },
        { question: "Is Newport Avenue Landscaping licensed and insured in Oregon?", answer: "Yes. Newport Avenue Landscaping holds Oregon Landscape Contractor Bond #9153 (LCB #9153). We are fully licensed, bonded, and insured for all residential and commercial landscaping work in Bend and throughout Central Oregon. All work is performed by our own employees -- we never use subcontractors." },
        { question: "Do you offer free estimates in Bend, Oregon?", answer: "Absolutely. We offer complimentary, no-obligation estimates for all our landscaping services in Bend. Simply contact us to schedule a convenient time for a site visit. Our experts will assess your property, discuss your vision, and provide a detailed written proposal within 24–48 hours, ensuring a swift start to your project." },
        { question: "What areas of Bend do you serve?", answer: "Newport Avenue Landscaping proudly serves all areas of Bend, Oregon, including Awbrey Butte, Broken Top, NorthWest Crossing, Discovery West, River West, Old Bend, Bend Country Club, Brookswood, Larkspur, Shevlin Meadows, and the broader SE, SW, NE, and NW Bend regions. We also serve the unincorporated areas surrounding Bend including Tumalo, Powell Butte, and the Deschutes River corridor." },
        { question: "How does Bend's volcanic soil impact landscaping choices?", answer: "Bend's unique volcanic pumice soil is exceptionally well-draining but low in organic matter, which impacts plant nutrient uptake and water retention. This requires careful soil amendment with compost and other organic materials to improve fertility and structure. Our landscaping experts in Bend specialize in selecting plants that thrive in these conditions and implementing proper soil preparation techniques to ensure the long-term health of your landscape. We also design irrigation systems specifically calibrated for pumice soil's fast drainage rate." },
        { question: "Do you do fire-wise landscaping in Bend?", answer: "Yes -- fire-wise landscaping is an important consideration for many Bend properties, particularly those near the urban-wildland interface on the west side and in areas like Awbrey Butte, Tumalo, and the Deschutes River corridor. We design fire-wise landscapes that reduce fuel loads around structures while maintaining beauty and curb appeal. This includes selecting fire-resistant plants, creating defensible space zones, and using non-combustible hardscaping materials near the home." },
      ]}
      mapEmbedUrl="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d47226.85!2d-121.3153!3d44.0582!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54b8c0ffa5d3d251%3A0x1088e7acc720d1b4!2sBend%2C%20OR!5e0!3m2!1sen!2sus!4v1713400000000"
/>
  );
}
