import CityPageLayout from "@/components/CityPageLayout";

export default function MadrasPage() {
  return (
    <CityPageLayout
      city="Madras"
      region="Central Oregon"
      heroImage="/manus-storage/NewportLandscapingRVParkDay2Photos2_8e8d0bb1.jpg"
      heroPosition="center 60%"
      tagline="Expert Landscaping & Lawn Care Services in Madras, Oregon"
      seoTitle="Madras Landscaping Oregon | Professional Lawn Care & Design | Newport Avenue"
      seoDescription="Premier Madras landscaping and lawn care services by Newport Avenue Landscaping. LCB #9153. Custom design, irrigation, xeriscaping, and maintenance for Jefferson County properties. Free estimates."
      canonicalPath="/landscaping/madras"
      intro="Newport Avenue Landscaping has proudly served the Madras community for many years, bringing our award-winning expertise to properties across Jefferson County. We understand the unique charm and agricultural heritage of Madras -- from the bustling city center and the Sahalee subdivision to the expansive agricultural outskirts and the scenic Round Butte area near the Deschutes and Crooked River confluence. Madras is one of Central Oregon's warmest and sunniest communities, and that climate creates both exceptional growing opportunities and real landscaping challenges that demand genuine local expertise. Our team designs and installs landscapes that embrace the warm Zone 6b/7a growing season while conserving the irrigation district water that makes Madras's lush properties possible. Whether you are looking for a comprehensive lawn care program, a custom xeriscape design, a new irrigation system, or a full outdoor living space with a patio and fire feature, Newport Avenue delivers the same quality and craftsmanship to Madras that we bring to every community we serve across Central Oregon. All work is performed by our own licensed crew -- we never use subcontractors -- and every installation project is backed by our 5-year workmanship warranty."
      communityNote="Madras, nestled in the high desert of Jefferson County, boasts a Zone 6b/7a climate that makes it one of the warmest cities in Central Oregon, with notably hot summers, long sunny days, and less snowfall than communities like Sisters or La Pine. This warmer, more arid environment -- combined with the availability of irrigation district water from the North Unit Irrigation District -- significantly influences landscaping decisions for Madras properties. The local soil is often a mix of volcanic and alluvial deposits from the Crooked and Deschutes River systems, requiring careful consideration for nutrient management and water retention to support lush lawns and vibrant plantings. Madras properties near the Round Butte Overlook and the Sahalee area often have spectacular views that deserve landscape designs that frame and enhance them. The city's agricultural roots also mean that many Madras properties are larger than typical suburban lots, creating opportunities for expansive landscape designs with fruit trees, vegetable gardens, and large irrigated turf areas alongside ornamental beds. Our designers are experienced with the full range of Madras property types -- from compact in-town residential lots to larger acreage properties on the city's outskirts -- and we tailor every design to the specific conditions, goals, and budget of each client."
      services={[
        { icon: "maintenance", name: "Madras Lawn Care & Maintenance", description: "Keep your Madras lawn pristine with our comprehensive lawn care services, including mowing, fertilization, weed control, and aeration tailored for the local Zone 6b/7a climate. We ensure your turf remains healthy and vibrant through Madras's hot summers and mild winters. Our maintenance crews are on a consistent schedule -- your lawn is never forgotten or skipped.", href: "/services/lawn-service" },
        { icon: "sprinklers", name: "Efficient Madras Irrigation Systems", description: "Design and installation of water-efficient irrigation systems for Madras properties, crucial for thriving landscapes in this arid region. Our solutions maximize water usage, leveraging available North Unit Irrigation District water effectively. We also perform annual sprinkler activations in spring and blowouts in fall to protect your system from freeze damage.", href: "/services/irrigation" },
        { icon: "design", name: "Custom Madras Landscape Design", description: "Transform your Madras property with bespoke landscape designs that reflect your vision and thrive in the local Zone 6b/7a climate. From xeriscaping to vibrant garden beds, we create stunning outdoor living spaces with CAD-based design plans and detailed plant and material specifications. Our designers understand Madras's unique soil and sun exposure conditions.", href: "/services/landscape-design" },
        { icon: "outdoor", name: "Madras Outdoor Living Spaces", description: "Enhance your Madras home with custom outdoor living features like paver patios, fire pits, outdoor kitchens, and pergolas -- perfect for enjoying the warm Central Oregon evenings. Madras's long, warm summers make outdoor living spaces an especially valuable investment. We design spaces for relaxation and entertainment that complement your home and landscape.", href: "/services/outdoor-living" },
        { icon: "architecture", name: "Sustainable Madras Xeriscaping", description: "Specialized xeriscaping services for Madras, focusing on drought-tolerant plants and water-wise designs that conserve water and reduce maintenance. Ideal for the arid conditions of Jefferson County, our xeriscape designs use native and adapted plants that thrive in Madras's heat while dramatically reducing water bills and maintenance time.", href: "/services/xeriscaping" },
        { icon: "commercial", name: "Commercial Landscaping in Madras", description: "Professional commercial landscaping services for businesses, retail centers, and public spaces across Madras, ensuring attractive and well-maintained properties year-round. We handle everything from routine lawn care and irrigation maintenance to large-scale landscape installations for new commercial developments in Jefferson County.", href: "/services/commercial-maintenance" },
      ]}
      whyUs={[
        "Over 21 years of dedicated landscaping service in Central Oregon, including the Madras and Jefferson County community.",
        "Oregon Landscape Contractor Bond #9153 (LCB #9153) -- fully licensed, bonded, and insured.",
        "A large team of 150+ in-house staff ensures consistent quality and timely project completion.",
        "Deep understanding of Madras's unique Zone 6b/7a climate, soil, and irrigation district water conditions.",
        "We never use subcontractors, guaranteeing accountability and superior craftsmanship on every Madras project.",
        "5-year workmanship warranty on all installation projects -- one of the strongest guarantees in the industry."
      ]}
      nearbyAreas={[
        { label: "Redmond", href: "/landscaping/redmond" },
        { label: "Culver", href: "/landscaping/culver" },
        { label: "Terrebonne", href: "/landscaping/terrebonne" },
        { label: "Crooked River Ranch", href: "/landscaping/crooked-river-ranch" },
        { label: "Prineville", href: "/landscaping/prineville" },
        { label: "Warm Springs", href: "/landscaping/warm-springs" }
      ]}
      ctaNote="Ready to transform your Madras property? Contact Newport Avenue Landscaping today for a free, no-obligation estimate. Our team is known for quick response times and can discuss seasonal programs designed specifically for the Madras climate. Let us bring our expertise to your home or business, ensuring your landscape thrives beautifully in Jefferson County."
      faqs={[
        { question: "How much does landscaping cost in Madras, Oregon?", answer: "Landscaping costs in Madras vary based on project scope and materials. For typical Madras lawn care services, expect prices starting around $97 per service. Larger projects like property cleanups generally range from $600, while irrigation system installations can be $1,600–$2,000 per zone. Comprehensive landscape design and installation projects in Madras, depending on complexity and size, can range from $15,000 to $80,000 or more, reflecting the quality and custom nature of our work. We provide detailed written estimates after a free site visit." },
        { question: "What landscaping services does Newport Avenue offer in Madras?", answer: "Newport Avenue Landscaping provides a full spectrum of services to Madras residents and businesses. This includes expert lawn care and maintenance, custom landscape design and installation, efficient irrigation system setup and repair, and the creation of stunning outdoor living spaces with patios, fire features, and pergolas. We also specialize in sustainable xeriscaping solutions and comprehensive commercial landscaping, all tailored to the unique needs of the Madras environment." },
        { question: "Is Newport Avenue Landscaping licensed and insured in Oregon?", answer: "Yes. Newport Avenue Landscaping holds Oregon Landscape Contractor Bond #9153 (LCB #9153). We are fully licensed, bonded, and insured for all residential and commercial landscaping work in Madras and throughout Central Oregon. All work is performed by our own employees -- we never use subcontractors -- ensuring accountability and consistent quality on every project." },
        { question: "Do you offer free estimates in Madras, Oregon?", answer: "Absolutely. Newport Avenue Landscaping is pleased to offer free, no-obligation estimates for all our services in Madras. We pride ourselves on a prompt response time, typically scheduling a site visit within a few business days to thoroughly assess your property and discuss your specific landscaping needs. This personalized approach ensures an accurate and transparent quote for your Madras project." },
        { question: "What areas of Madras do you serve?", answer: "We proudly serve all key areas within Madras and its surrounding communities in Jefferson County. This includes the Sahalee subdivision, Crestview Hills, the Round Butte area, the Madras Airport area, and the agricultural outskirts. Our services also extend to Culver, Terrebonne, Crooked River Ranch, and other Jefferson County communities." },
        { question: "How does Madras's arid climate affect landscaping choices?", answer: "Madras's arid climate, characterized by hot summers and less precipitation than other Central Oregon communities, significantly influences optimal landscaping choices. We recommend drought-tolerant plants, efficient drip irrigation systems, and thoughtful xeriscape designs to conserve water and ensure plant health. Our experts select species that thrive in Zone 6b/7a, focusing on native and adapted plants that can withstand the intense summer heat while maintaining aesthetic appeal. The availability of North Unit Irrigation District water for many Madras properties also opens up options for traditional irrigated lawns and ornamental gardens." },
        { question: "Can you help with landscaping for acreage properties near Madras?", answer: "Yes -- we regularly work on larger acreage properties in the Madras area. Larger lots present different opportunities and challenges than typical suburban properties: longer irrigation runs, more extensive soil preparation, the potential for orchard or vegetable garden integration, and the need for thoughtful design to create defined outdoor spaces within a larger canvas. Our design team is experienced with acreage properties and can help you create a landscape plan that makes the most of your land while keeping maintenance manageable." },
      ]}
      mapEmbedUrl="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d23548.5!2d-121.1296!3d44.6329!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54b8f0b8b8b8b8b8%3A0x1088e7acc720d1b4!2sMadras%2C%20OR!5e0!3m2!1sen!2sus!4v1713400000007"
/>
  );
}
