import CityPageLayout from "@/components/CityPageLayout";

export default function TumaloPage() {
  return (
    <CityPageLayout
      city="Tumalo"
      region="Central Oregon"
      heroImage="/manus-storage/NewportAveLandcaping-9_97b731b0_1204d3ca.webp"
      heroPosition="center 40%"
      tagline="Transforming Tumalo's Rural Beauty into Exquisite Outdoor Living Spaces"
      seoTitle="Tumalo Landscaping Oregon & Tumalo Lawn Care Experts | Newport Avenue Landscaping"
      seoDescription="Newport Avenue Landscaping offers premier landscaping and lawn care services in Tumalo, Oregon. From design to maintenance, get a free estimate today! LCB #9153."
      canonicalPath="/landscaping/tumalo"
      intro="Newport Avenue Landscaping has proudly served the unique community of Tumalo for many years, deeply understanding its rural charm, agricultural roots, and the distinctive character of its properties. Tumalo sits just northwest of Bend along the Deschutes River corridor, and its combination of larger lots, irrigation district water access, and stunning high-desert scenery creates landscaping opportunities that are unlike anything you will find in a typical suburban neighborhood. Our commitment extends to properties along the Tumalo Creek corridor, expansive rural acreage, and homes near Tumalo State Park -- bringing unparalleled expertise to every project. We specialize in enhancing the natural beauty of Tumalo, ensuring that each landscape design harmonizes with the surrounding juniper and sage environment while creating functional, beautiful outdoor spaces that reflect the way Tumalo residents actually live. Whether you are looking for a comprehensive lawn care program for a large irrigated property, a fire-wise xeriscape design that reduces your risk and maintenance burden, or a complete outdoor living transformation with a patio, fire feature, and water feature, Newport Avenue delivers the same quality and craftsmanship to Tumalo that we bring to every community we serve. All work is performed by our own licensed crew -- we never use subcontractors -- and every installation project is backed by our 90-day plant warranty and 1-year irrigation warranty."
      communityNote="Tumalo, nestled in Central Oregon just northwest of Bend, shares a similar high-desert climate but often experiences slightly cooler temperatures, falling within USDA Zone 6a. This environment features hot, dry summers and cold winters, with approximately 11 inches of annual precipitation. A defining characteristic of Tumalo is its rural character, larger lots, and significant agricultural heritage -- many Tumalo properties benefit from North Unit or Central Oregon Irrigation District water, which opens up options for traditional irrigated lawns and expansive ornamental gardens that would be impractical on well water alone. The volcanic pumice soil, while well-draining, is low in organic matter and requires careful amendment to support diverse plant life. Tumalo's proximity to the urban-wildland interface also makes fire-wise landscaping a genuine consideration for many properties -- the combination of dry summers, juniper and sage native vegetation, and prevailing westerly winds creates real fire risk that thoughtful landscape design can help mitigate. Our designers are experienced with all of these Tumalo-specific variables, from maximizing irrigation district water efficiency to creating defensible space zones that are both functional and visually appealing. We also understand the unique character of Tumalo's most distinctive areas -- the Tumalo Creek corridor with its riparian vegetation, the Cline Falls area, and the rural acreage properties along Tumalo Road -- and we design landscapes that feel right for each specific location."
      services={[
        { icon: "maintenance", name: "Tumalo Lawn Care & Maintenance", description: "Keep your Tumalo property looking pristine with our comprehensive lawn care services, including mowing, fertilization, weed control, and aeration. We understand the specific needs of Tumalo's larger lots and rural settings, ensuring a healthy, vibrant lawn all season long. Our maintenance crews are on a consistent schedule -- your property is never forgotten or skipped.", href: "/services/lawn-service" },
        { icon: "sprinklers", name: "Tumalo Irrigation Systems", description: "Efficient irrigation is vital for Tumalo's landscapes, especially with access to irrigation district water. Our experts design, install, and maintain smart irrigation systems that conserve water while keeping your plants hydrated and thriving in the local climate. We also perform annual sprinkler activations in spring and blowouts in fall to protect your system from Tumalo's hard winter freezes.", href: "/services/irrigation" },
        { icon: "design", name: "Custom Landscape Design in Tumalo", description: "From conceptualization to completion, our landscape design services transform your Tumalo acreage into a personalized outdoor oasis. We create CAD-based design plans that integrate native plants, sustainable practices, and thoughtful hardscaping that complements Tumalo's rural aesthetic and climate. Our designers are experienced with the larger lot sizes and varied terrain typical of Tumalo properties.", href: "/services/landscape-design" },
        { icon: "outdoor", name: "Outdoor Living Spaces for Tumalo Homes", description: "Enhance your Tumalo home with custom outdoor living features like paver patios, fire pits, outdoor kitchens, and pergolas. We create functional and beautiful spaces perfect for enjoying Tumalo's serene evenings and expansive views of the Cascades and high desert. Tumalo's larger lots often allow for outdoor living spaces that simply are not possible on smaller suburban properties.", href: "/services/outdoor-living" },
        { icon: "architecture", name: "Xeriscaping & Fire-Wise Landscaping", description: "Given Tumalo's high-desert climate and proximity to the urban-wildland interface, xeriscaping and fire-wise design are excellent choices for water conservation, low maintenance, and property protection. Our designs incorporate beautiful, drought-tolerant plants that flourish in Tumalo's conditions while creating the defensible space zones recommended by fire safety experts.", href: "/services/xeriscaping" },
        { icon: "commercial", name: "Commercial Landscaping & Snow Removal", description: "Newport Avenue Landscaping provides reliable commercial landscaping and snow removal services for businesses and properties throughout Tumalo. We ensure your commercial space is well-maintained year-round, reflecting professionalism and care. Our equipment and crew size allow us to handle large-scale commercial and rural properties efficiently.", href: "/services/snow-removal" },
      ]}
      whyUs={[
        "Over 21 years of dedicated landscaping experience in Central Oregon, deeply rooted in the Tumalo community.",
        "Oregon Landscape Contractor Bond #9153 (LCB #9153) -- fully licensed, bonded, and insured for your peace of mind.",
        "A robust team of 150+ in-house staff, ensuring consistent quality and timely project completion without relying on subcontractors.",
        "Profound local knowledge of Tumalo's unique climate, irrigation district water, and fire-wise landscaping requirements.",
        "We never use subcontractors, guaranteeing Newport Avenue's high standards on every job.",
        "90-day plant warranty and 1-year irrigation warranty on all installation projects."
      ]}
      nearbyAreas={[
        { label: "Bend", href: "/landscaping/bend" },
        { label: "Redmond", href: "/landscaping/redmond" },
        { label: "Sisters", href: "/landscaping/sisters" },
        { label: "Powell Butte", href: "/landscaping/powell-butte" },
        { label: "Alfalfa", href: "/landscaping/alfalfa" },
        { label: "Cline Falls", href: "/landscaping/cline-falls" },
        { label: "Terrebonne", href: "/landscaping/terrebonne" },
        { label: "Crooked River Ranch", href: "/landscaping/crooked-river-ranch" }
      ]}
      ctaNote="Ready to transform your Tumalo property into the landscape of your dreams? Contact Newport Avenue Landscaping today for a free, no-obligation estimate. Our team is known for prompt responses and can discuss seasonal programs designed specifically for Tumalo's unique environment, ensuring your outdoor space thrives year-round."
      faqs={[
        { question: "How much does landscaping cost in Tumalo, Oregon?", answer: "Landscaping costs in Tumalo vary widely based on project scope and materials. For basic lawn care services, residents can expect to pay from $97 per service. Larger projects like seasonal cleanups typically start from $600, while irrigation system installations can range from $1,600 to $2,000 per zone. Full landscape design and installation projects, especially for Tumalo's larger acreage properties, can range from $15,000 to $80,000+, depending on complexity and features. We provide detailed, transparent written estimates after a free site visit." },
        { question: "What landscaping services does Newport Avenue offer in Tumalo?", answer: "Newport Avenue Landscaping offers a comprehensive suite of services tailored for Tumalo properties. This includes expert lawn care and maintenance, custom landscape design, efficient irrigation system installation and repair, and the creation of stunning outdoor living spaces with patios, fire features, and pergolas. We also specialize in xeriscaping, fire-wise landscaping, retaining walls, landscape lighting, and commercial landscaping solutions, all designed to thrive in Tumalo's unique climate and rural setting." },
        { question: "Is Newport Avenue Landscaping licensed and insured in Oregon?", answer: "Yes. Newport Avenue Landscaping holds Oregon Landscape Contractor Bond #9153 (LCB #9153). We are fully licensed, bonded, and insured for all residential and commercial landscaping work in Tumalo and throughout Central Oregon. All work is performed by our own employees -- we never use subcontractors -- ensuring accountability and consistent quality on every project." },
        { question: "Do you offer free estimates in Tumalo, Oregon?", answer: "Absolutely. Newport Avenue Landscaping is pleased to offer free, no-obligation estimates for all potential landscaping projects in Tumalo, Oregon. We pride ourselves on a quick response time, typically within 24–48 hours, to schedule a convenient site visit. During this visit, our experts will assess your property, discuss your vision, and provide a detailed written quote tailored to your specific needs and the unique characteristics of your Tumalo landscape." },
        { question: "What areas of Tumalo do you serve?", answer: "We proudly serve all key areas within and around Tumalo, Oregon. This includes properties along the Tumalo Creek corridor, expansive rural acreage, homes near Tumalo State Park, and residences along the Tumalo Road corridor. Our services also extend to the Cline Falls area and other surrounding communities, ensuring comprehensive coverage for the entire Tumalo region." },
        { question: "How does Tumalo's irrigation district water affect landscaping choices?", answer: "Tumalo's access to irrigation district water is a significant advantage for landscaping, offering a reliable and often more cost-effective water source for larger properties. This allows for a broader range of plant choices and more extensive lawn areas compared to areas solely reliant on well water. Our team specializes in designing irrigation systems that efficiently utilize this resource, ensuring optimal plant health while adhering to water conservation principles." },
        { question: "Do you do fire-wise landscaping in Tumalo?", answer: "Yes -- fire-wise landscaping is an important consideration for many Tumalo properties, particularly those near the urban-wildland interface and in areas with juniper and sage native vegetation. We design fire-wise landscapes that reduce fuel loads around structures while maintaining beauty and curb appeal. This includes selecting fire-resistant plants, creating defensible space zones at the recommended distances from structures, and using non-combustible hardscaping materials near the home. Many Tumalo homeowners find that fire-wise landscaping also significantly reduces their maintenance burden." },
      ]}
      mapEmbedUrl="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11774.2!2d-121.2985!3d44.1468!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54b8d0b8b8b8b8b8%3A0x1088e7acc720d1b4!2sTumalo%2C%20OR!5e0!3m2!1sen!2sus!4v1713400000004"
/>
  );
}
