/**
 * generate-sitemap.mjs
 * Build-time script: reads all public routes and writes client/public/sitemap.xml
 * Run with: node scripts/generate-sitemap.mjs
 * Excludes all /admin/* routes.
 */

import { writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const BASE_URL = "https://newportavelandscaping.com";
const OUTPUT_PATH = resolve(__dirname, "../client/public/sitemap.xml");

// ─── All public routes ───────────────────────────────────────────────────────
// Sourced from App.tsx — every <Route path=...> that is NOT /admin/*
// Priority and changefreq follow SEO best practices:
//   1.0 = homepage
//   0.9 = core service/portfolio pages
//   0.8 = city/service-area pages
//   0.7 = resource/cost-guide pages
//   0.6 = blog posts, misc

const routes = [
  // ── Core SEO landing pages ──────────────────────────────────────────────
  { path: "/",                              priority: "1.0", changefreq: "weekly"  },
  { path: "/landscaping-bend-oregon",       priority: "0.9", changefreq: "monthly" },
  { path: "/paver-patios-bend",             priority: "0.9", changefreq: "monthly" },
  { path: "/irrigation-bend-oregon",        priority: "0.9", changefreq: "monthly" },
  { path: "/landscape-design-bend",         priority: "0.9", changefreq: "monthly" },
  { path: "/commercial-landscaping-bend",   priority: "0.9", changefreq: "monthly" },
  { path: "/paver-patios-bend/concrete-pavers",         priority: "0.8", changefreq: "monthly" },
  { path: "/landscape-design-bend/hoa-design",          priority: "0.8", changefreq: "monthly" },
  { path: "/landscape-design-bend/modern-design",       priority: "0.8", changefreq: "monthly" },

  // ── Main pages ──────────────────────────────────────────────────────────
  { path: "/about",           priority: "0.8", changefreq: "monthly" },
  { path: "/commercial",      priority: "0.8", changefreq: "monthly" },
  { path: "/maintenance",     priority: "0.9", changefreq: "monthly" },
  { path: "/services",        priority: "0.9", changefreq: "monthly" },
  { path: "/our-work",        priority: "0.8", changefreq: "weekly"  },
  { path: "/contact",         priority: "0.8", changefreq: "monthly" },
  { path: "/blog",            priority: "0.7", changefreq: "weekly"  },
  { path: "/resources",       priority: "0.8", changefreq: "weekly"  },
  { path: "/service-areas",   priority: "0.8", changefreq: "monthly" },
  { path: "/bend-neighborhoods", priority: "0.7", changefreq: "monthly" },
  { path: "/privacy-policy",  priority: "0.4", changefreq: "yearly"  },
  { path: "/membership",      priority: "0.7", changefreq: "monthly" },
  { path: "/terms",           priority: "0.4", changefreq: "yearly"  },
  { path: "/careers",         priority: "0.6", changefreq: "monthly" },
  { path: "/opt-out",         priority: "0.6", changefreq: "monthly" },
  { path: "/schedule-services", priority: "0.9", changefreq: "monthly" },

  // ── Maintenance sub-pages ───────────────────────────────────────────────
  { path: "/services/lawn-service",          priority: "0.9", changefreq: "monthly" },
  { path: "/services/commercial-maintenance",priority: "0.8", changefreq: "monthly" },
  { path: "/maintenance/commercial-hoa",     priority: "0.8", changefreq: "monthly" },
  { path: "/services/aeration",              priority: "0.8", changefreq: "monthly" },
  { path: "/services/sprinkler-activation",  priority: "0.8", changefreq: "monthly" },
  { path: "/services/sprinkler-blowout",     priority: "0.8", changefreq: "monthly" },
  { path: "/services/snow-removal",          priority: "0.8", changefreq: "monthly" },
  { path: "/services/lawn-fungus",           priority: "0.7", changefreq: "monthly" },

  // ── Installation / service sub-pages ────────────────────────────────────
  { path: "/services/landscape-design",      priority: "0.9", changefreq: "monthly" },
  { path: "/services/irrigation",            priority: "0.9", changefreq: "monthly" },
  { path: "/services/sprinkler-repair",      priority: "0.8", changefreq: "monthly" },
  { path: "/services/pavers",                priority: "0.9", changefreq: "monthly" },
  { path: "/services/water-features",        priority: "0.8", changefreq: "monthly" },
  { path: "/services/outdoor-living",        priority: "0.8", changefreq: "monthly" },
  { path: "/services/fire-features",         priority: "0.8", changefreq: "monthly" },
  { path: "/services/landscape-lighting",    priority: "0.8", changefreq: "monthly" },
  { path: "/services/xeriscaping",           priority: "0.9", changefreq: "monthly" },
  { path: "/services/retaining-walls",       priority: "0.8", changefreq: "monthly" },
  { path: "/services/drainage",              priority: "0.8", changefreq: "monthly" },
  { path: "/services/firewise-landscaping",  priority: "0.8", changefreq: "monthly" },
  { path: "/services/water-wise-landscaping",priority: "0.8", changefreq: "monthly" },

  // ── City landing pages ───────────────────────────────────────────────────
  { path: "/landscaping/bend",               priority: "0.9", changefreq: "monthly" },
  { path: "/landscaping/redmond",            priority: "0.8", changefreq: "monthly" },
  { path: "/landscaping/sisters",            priority: "0.8", changefreq: "monthly" },
  { path: "/landscaping/sunriver",           priority: "0.8", changefreq: "monthly" },
  { path: "/landscaping/tumalo",             priority: "0.8", changefreq: "monthly" },
  { path: "/landscaping/prineville",         priority: "0.8", changefreq: "monthly" },
  { path: "/landscaping/la-pine",            priority: "0.8", changefreq: "monthly" },
  { path: "/landscaping/madras",             priority: "0.8", changefreq: "monthly" },
  { path: "/landscaping/eagle-crest",        priority: "0.8", changefreq: "monthly" },
  { path: "/landscaping/powell-butte",       priority: "0.8", changefreq: "monthly" },
  { path: "/landscaping/terrebonne",         priority: "0.7", changefreq: "monthly" },
  { path: "/landscaping/crooked-river-ranch",priority: "0.7", changefreq: "monthly" },
  { path: "/landscaping/alfalfa",            priority: "0.7", changefreq: "monthly" },
  { path: "/landscaping/cline-falls",        priority: "0.7", changefreq: "monthly" },

  // ── Blog posts ───────────────────────────────────────────────────────────
  { path: "/blog/climate-change-landscaping",           priority: "0.6", changefreq: "yearly"  },
  { path: "/blog/seasonal-landscaping-guide",           priority: "0.6", changefreq: "yearly"  },
  { path: "/blog/xeriscape-landscaping-bend-oregon",    priority: "0.6", changefreq: "yearly"  },
  { path: "/blog/sprinkler-winterization-bend-oregon",  priority: "0.6", changefreq: "yearly"  },
  { path: "/blog/paver-patio-ideas-bend-oregon",        priority: "0.6", changefreq: "yearly"  },
  { path: "/blog/lawn-care-bend-oregon",                priority: "0.6", changefreq: "yearly"  },

  // ── Portfolio project pages ──────────────────────────────────────────────
  { path: "/portfolio/awbrey-butte-xeriscape",    priority: "0.7", changefreq: "yearly"  },
  { path: "/portfolio/awbrey-glenn-flagstone",    priority: "0.7", changefreq: "yearly"  },
  { path: "/portfolio/backyard-renovation",       priority: "0.7", changefreq: "yearly"  },
  { path: "/portfolio/broken-top-water-feature",  priority: "0.7", changefreq: "yearly"  },
  { path: "/portfolio/broken-top-xeriscape",      priority: "0.7", changefreq: "yearly"  },
  { path: "/portfolio/century-drive",             priority: "0.7", changefreq: "yearly"  },
  { path: "/portfolio/east-bend-landscape",       priority: "0.7", changefreq: "yearly"  },
  { path: "/portfolio/nw-bend-backyard",          priority: "0.7", changefreq: "yearly"  },
  { path: "/portfolio/paver-patio-firepit",       priority: "0.7", changefreq: "yearly"  },
  { path: "/portfolio/sw-bend-backyard",          priority: "0.7", changefreq: "yearly"  },
  { path: "/portfolio/bend-full-yard-transformation", priority: "0.7", changefreq: "yearly" },
  { path: "/portfolio/awbrey-butte-patio",        priority: "0.7", changefreq: "yearly"  },
  { path: "/portfolio/nw-bend-lighting",          priority: "0.7", changefreq: "yearly"  },
  { path: "/portfolio/westside-outdoor-living",   priority: "0.7", changefreq: "yearly"  },

  // ── SEO Resource pages ───────────────────────────────────────────────────
  { path: "/resources/paver-patio-cost-bend-oregon",          priority: "0.7", changefreq: "monthly" },
  { path: "/resources/sprinkler-system-cost-bend-oregon",     priority: "0.7", changefreq: "monthly" },
  { path: "/resources/xeriscape-cost-bend-oregon",            priority: "0.7", changefreq: "monthly" },
  { path: "/resources/landscape-design-cost-bend-oregon",     priority: "0.7", changefreq: "monthly" },
  { path: "/resources/retaining-wall-cost-bend-oregon",       priority: "0.7", changefreq: "monthly" },
  { path: "/resources/sod-installation-cost-bend-oregon",     priority: "0.7", changefreq: "monthly" },
  { path: "/resources/outdoor-lighting-cost-bend-oregon",     priority: "0.7", changefreq: "monthly" },
  { path: "/resources/water-feature-cost-bend-oregon",        priority: "0.7", changefreq: "monthly" },
  { path: "/resources/lawn-maintenance-cost-bend-oregon",     priority: "0.7", changefreq: "monthly" },
  { path: "/resources/fire-pit-patio-cost-bend-oregon",       priority: "0.7", changefreq: "monthly" },
  { path: "/resources/best-plants-central-oregon-xeriscape",  priority: "0.7", changefreq: "monthly" },
  { path: "/resources/when-to-aerate-lawn-bend-oregon",       priority: "0.7", changefreq: "monthly" },
  { path: "/resources/sprinkler-winterization-guide-bend",    priority: "0.7", changefreq: "monthly" },
  { path: "/resources/how-to-choose-landscaper-bend-oregon",  priority: "0.7", changefreq: "monthly" },
  { path: "/resources/bend-oregon-turf-rebate-program",       priority: "0.7", changefreq: "monthly" },
  { path: "/resources/irrigation-repair-bend-oregon",         priority: "0.7", changefreq: "monthly" },
  { path: "/resources/commercial-landscaping-bend-oregon",    priority: "0.7", changefreq: "monthly" },
  { path: "/resources/snow-removal-bend-oregon",              priority: "0.7", changefreq: "monthly" },
  { path: "/resources/landscape-lighting-bend-oregon",        priority: "0.7", changefreq: "monthly" },
  { path: "/resources/natural-stone-vs-concrete-pavers-bend-oregon", priority: "0.7", changefreq: "monthly" },
  { path: "/resources/gas-vs-propane-fire-pit-bend-oregon",   priority: "0.7", changefreq: "monthly" },
  { path: "/resources/irrigation-faq-bend-oregon",            priority: "0.7", changefreq: "monthly" },
  { path: "/resources/paver-patio-faq-bend-oregon",           priority: "0.7", changefreq: "monthly" },
  { path: "/resources/xeriscape-faq-bend-oregon",             priority: "0.7", changefreq: "monthly" },
  { path: "/resources/lawn-care-cost-bend-oregon",            priority: "0.7", changefreq: "monthly" },
  { path: "/resources/lawn-aeration-cost-bend-oregon",        priority: "0.7", changefreq: "monthly" },
  { path: "/resources/backflow-preventer-testing-bend-oregon",priority: "0.7", changefreq: "monthly" },
  { path: "/resources/snow-removal-cost-bend-oregon",         priority: "0.7", changefreq: "monthly" },
  { path: "/resources/irrigation-repair-cost-bend-oregon",    priority: "0.7", changefreq: "monthly" },
  { path: "/resources/commercial-landscaping-cost-bend-oregon",priority: "0.7", changefreq: "monthly" },
  { path: "/resources/lawn-fungus-treatment-bend-oregon",     priority: "0.7", changefreq: "monthly" },
  // Extended resource pages
  { path: "/resources/hoa-landscaping-bend-oregon",           priority: "0.7", changefreq: "monthly" },
  { path: "/resources/landscape-transformation-bend-oregon",  priority: "0.7", changefreq: "monthly" },
  { path: "/resources/landscape-design-ideas-bend-oregon",    priority: "0.7", changefreq: "monthly" },
  { path: "/resources/landscape-maintenance-plan-bend-oregon",priority: "0.7", changefreq: "monthly" },
  { path: "/resources/landscape-warranty-bend-oregon",        priority: "0.7", changefreq: "monthly" },
  { path: "/resources/landscaping-company-bend-oregon",       priority: "0.7", changefreq: "monthly" },
  { path: "/resources/landscaping-cost-guide-bend-oregon",    priority: "0.7", changefreq: "monthly" },
  { path: "/resources/landscaping-seasons-bend-oregon",       priority: "0.7", changefreq: "monthly" },
  { path: "/resources/landscaping-tips-bend-oregon",          priority: "0.7", changefreq: "monthly" },
  { path: "/resources/new-construction-landscaping-bend-oregon",priority: "0.7", changefreq: "monthly" },
  { path: "/resources/landscaping-home-value-bend-oregon",    priority: "0.7", changefreq: "monthly" },
  { path: "/resources/bend-turf-rebate-program",              priority: "0.7", changefreq: "monthly" },
  { path: "/resources/best-plants-xeriscape-central-oregon",  priority: "0.7", changefreq: "monthly" },
  { path: "/resources/boulder-landscaping-cost-bend-oregon",  priority: "0.7", changefreq: "monthly" },
  { path: "/resources/central-oregon-landscaping-guide",      priority: "0.7", changefreq: "monthly" },
  { path: "/resources/drainage-solutions-cost-bend-oregon",   priority: "0.7", changefreq: "monthly" },
  { path: "/resources/drip-vs-spray-irrigation-bend-oregon",  priority: "0.7", changefreq: "monthly" },
  { path: "/resources/driveway-paver-cost-bend-oregon",       priority: "0.7", changefreq: "monthly" },
  { path: "/resources/fall-landscaping-guide-bend-oregon",    priority: "0.7", changefreq: "monthly" },
  { path: "/resources/faq-irrigation-bend-oregon",            priority: "0.7", changefreq: "monthly" },
  { path: "/resources/faq-lawn-care-bend-oregon",             priority: "0.7", changefreq: "monthly" },
  { path: "/resources/faq-outdoor-lighting-bend-oregon",      priority: "0.7", changefreq: "monthly" },
  { path: "/resources/faq-paver-patio-bend-oregon",           priority: "0.7", changefreq: "monthly" },
  { path: "/resources/faq-retaining-wall-bend-oregon",        priority: "0.7", changefreq: "monthly" },
  { path: "/resources/faq-snow-removal-bend-oregon",          priority: "0.7", changefreq: "monthly" },
  { path: "/resources/faq-water-feature-bend-oregon",         priority: "0.7", changefreq: "monthly" },
  { path: "/resources/faq-xeriscape-bend-oregon",             priority: "0.7", changefreq: "monthly" },
  { path: "/resources/fencing-cost-bend-oregon",              priority: "0.7", changefreq: "monthly" },
  { path: "/resources/how-to-install-drip-irrigation-bend-oregon",priority: "0.7", changefreq: "monthly" },
  { path: "/resources/how-to-maintain-paver-patio-bend-oregon",priority: "0.7", changefreq: "monthly" },
  { path: "/resources/how-to-plant-trees-bend-oregon",        priority: "0.7", changefreq: "monthly" },
  { path: "/resources/how-to-prevent-lawn-fungus-bend-oregon",priority: "0.7", changefreq: "monthly" },
  { path: "/resources/how-to-read-landscape-proposal-bend-oregon",priority: "0.7", changefreq: "monthly" },
  { path: "/resources/understanding-soil-bend-oregon",        priority: "0.7", changefreq: "monthly" },
  { path: "/resources/how-to-select-pavers-bend-oregon",      priority: "0.7", changefreq: "monthly" },
  { path: "/resources/how-to-water-lawn-bend-oregon",         priority: "0.7", changefreq: "monthly" },
  { path: "/resources/how-to-xeriscape-bend-oregon",          priority: "0.7", changefreq: "monthly" },
  { path: "/resources/landscape-lighting-cost-bend-oregon",   priority: "0.7", changefreq: "monthly" },
  { path: "/resources/landscaping-bend-oregon",               priority: "0.7", changefreq: "monthly" },
  { path: "/resources/mulch-installation-cost-bend-oregon",   priority: "0.7", changefreq: "monthly" },
  { path: "/resources/native-vs-adapted-plants-bend-oregon",  priority: "0.7", changefreq: "monthly" },
  { path: "/resources/outdoor-kitchen-cost-bend-oregon",      priority: "0.7", changefreq: "monthly" },
  { path: "/resources/paver-walkway-cost-bend-oregon",        priority: "0.7", changefreq: "monthly" },
  { path: "/resources/pavers-vs-concrete-bend-oregon",        priority: "0.7", changefreq: "monthly" },
  { path: "/resources/perennial-garden-cost-bend-oregon",     priority: "0.7", changefreq: "monthly" },
  { path: "/resources/pergola-cost-bend-oregon",              priority: "0.7", changefreq: "monthly" },
  { path: "/resources/professional-vs-diy-landscaping-bend-oregon",priority: "0.7", changefreq: "monthly" },
  { path: "/resources/sod-vs-seed-bend-oregon",               priority: "0.7", changefreq: "monthly" },
  { path: "/resources/spring-landscaping-guide-bend-oregon",  priority: "0.7", changefreq: "monthly" },
  { path: "/resources/sprinkler-winterization-guide-bend-oregon",priority: "0.7", changefreq: "monthly" },
  { path: "/resources/summer-landscaping-guide-bend-oregon",  priority: "0.7", changefreq: "monthly" },
  { path: "/resources/tree-removal-cost-bend-oregon",         priority: "0.7", changefreq: "monthly" },
  { path: "/resources/winter-landscaping-guide-bend-oregon",  priority: "0.7", changefreq: "monthly" },
  { path: "/resources/xeriscape-vs-traditional-lawn-bend-oregon",priority: "0.7", changefreq: "monthly" },
  { path: "/resources/best-grass-bend-oregon",                priority: "0.7", changefreq: "monthly" },
  { path: "/resources/when-to-plant-bend-oregon",             priority: "0.7", changefreq: "monthly" },
  { path: "/resources/brown-lawn-bend-oregon",                priority: "0.7", changefreq: "monthly" },
  // Fire-Wise resources
  { path: "/resources/defensible-space-bend-oregon",          priority: "0.7", changefreq: "monthly" },
  { path: "/resources/deschutes-county-fire-hardening-requirements",priority: "0.7", changefreq: "monthly" },
  { path: "/resources/fire-resistant-plants-central-oregon",  priority: "0.7", changefreq: "monthly" },
  { path: "/resources/juniper-removal-bend-oregon",           priority: "0.7", changefreq: "monthly" },
  // Water-wise resources
  { path: "/resources/bend-watering-restrictions",            priority: "0.7", changefreq: "monthly" },
  { path: "/resources/bend-turf-replacement-rebate",          priority: "0.7", changefreq: "monthly" },
  { path: "/resources/water-wise-landscaping-bend-oregon",    priority: "0.7", changefreq: "monthly" },
  { path: "/resources/waterwise-communities-bend-hoa",        priority: "0.7", changefreq: "monthly" },

  // ── Neighborhood / Service Area pages ───────────────────────────────────
  { path: "/service-areas/awbrey-butte-landscaping",          priority: "0.8", changefreq: "monthly" },
  { path: "/service-areas/northwest-crossing-landscaping",    priority: "0.8", changefreq: "monthly" },
  { path: "/service-areas/broken-top-landscaping",            priority: "0.8", changefreq: "monthly" },
  { path: "/service-areas/discovery-west-landscaping",        priority: "0.8", changefreq: "monthly" },
  { path: "/service-areas/sunriver-landscaping",              priority: "0.8", changefreq: "monthly" },
  { path: "/service-areas/redmond-landscaping",               priority: "0.8", changefreq: "monthly" },
  { path: "/service-areas/powell-butte-landscaping",          priority: "0.8", changefreq: "monthly" },
  { path: "/service-areas/eagle-crest-landscaping",           priority: "0.8", changefreq: "monthly" },
  { path: "/service-areas/bend-country-club-landscaping",     priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/bend-east-side-landscaping",        priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/bend-south-landscaping",            priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/bend-westside-landscaping",         priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/brookswood-landscaping",            priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/century-drive-corridor-landscaping",priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/crooked-river-ranch",               priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/culver",                            priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/deschutes-river-woods-landscaping", priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/hunnell-road-area-landscaping",     priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/alfalfa-irrigation",                priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/crooked-river-ranch-irrigation",    priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/culver-irrigation",                 priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/madras-irrigation",                 priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/powell-butte-irrigation",           priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/terrebonne-irrigation",             priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/la-pine",                           priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/la-pine-landscape-design",          priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/prineville-landscape-design",       priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/redmond-landscape-design",          priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sisters-landscape-design",          priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sunriver-landscape-design",         priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/tumalo-landscape-design",           priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/larkspur-landscaping",              priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/lava-butte-area-landscaping",       priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/alfalfa-lawn-care",                 priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/crooked-river-ranch-lawn-care",     priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/culver-lawn-care",                  priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/la-pine-lawn-care",                 priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/madras-lawn-care",                  priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/powell-butte-lawn-care",            priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/prineville-lawn-care",              priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/redmond-lawn-care",                 priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sisters-lawn-care",                 priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sunriver-lawn-care",                priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/terrebonne-lawn-care",              priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/tumalo-lawn-care",                  priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/madras",                            priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/murphy-road-area-landscaping",      priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/northeast-bend-landscaping",        priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/old-mill-district-landscaping",     priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/orion-greens-landscaping",          priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/alfalfa-paver-patio",               priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/crooked-river-ranch-paver-patio",   priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/culver-paver-patio",                priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/la-pine-paver-patio",               priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/madras-paver-patio",                priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/powell-butte-paver-patio",          priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/prineville-paver-patio",            priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/redmond-paver-patio",               priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sisters-paver-patio",               priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sunriver-paver-patio",              priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/terrebonne-paver-patio",            priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/tumalo-paver-patio",                priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/prineville",                        priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/redmond",                           priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/river-west-landscaping",            priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/shevlin-meadows-landscaping",       priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/shevlin-park-area-landscaping",     priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sisters",                           priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/skyline-ranch-landscaping",         priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/southeast-bend-landscaping",        priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/la-pine-sprinkler-system",          priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/prineville-sprinkler-system",       priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/redmond-sprinkler-system",          priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sisters-sprinkler-system",          priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sunriver-sprinkler-system",         priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/tumalo-sprinkler-system",           priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/summit-west-landscaping",           priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sunriver",                          priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/terrebonne",                        priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/tetherow-landscaping",              priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/woodriver-village-landscaping",     priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/la-pine-xeriscape",                 priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/prineville-xeriscape",              priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/redmond-xeriscape",                 priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sisters-xeriscape",                 priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sunriver-xeriscape",                priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/tumalo-xeriscape",                  priority: "0.7", changefreq: "monthly" },
  // City-specific service pages (from old lazy imports)
  { path: "/service-areas/redmond-pavers",                    priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/redmond-irrigation",                priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/redmond-xeriscaping",               priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/redmond-landscape-design",          priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/redmond-lawn-service",              priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/redmond-snow-removal",              priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sisters-pavers",                    priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sisters-irrigation",                priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sisters-xeriscaping",               priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sisters-lawn-service",              priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sisters-snow-removal",              priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sunriver-pavers",                   priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sunriver-irrigation",               priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sunriver-lawn-service",             priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/sunriver-snow-removal",             priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/la-pine-pavers",                    priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/la-pine-irrigation",                priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/la-pine-lawn-service",              priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/la-pine-snow-removal",              priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/prineville-pavers",                 priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/prineville-irrigation",             priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/prineville-lawn-service",           priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/prineville-snow-removal",           priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/madras-pavers",                     priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/madras-irrigation",                 priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/madras-xeriscaping",                priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/madras-lawn-service",               priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/madras-snow-removal",               priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/tumalo-pavers",                     priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/tumalo-irrigation",                 priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/tumalo-xeriscaping",                priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/tumalo-lawn-service",               priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/tumalo-snow-removal",               priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/terrebonne-pavers",                 priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/terrebonne-irrigation",             priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/terrebonne-xeriscaping",            priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/terrebonne-lawn-service",           priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/terrebonne-snow-removal",           priority: "0.7", changefreq: "monthly" },
  { path: "/service-areas/old-bend-landscaping",              priority: "0.7", changefreq: "monthly" },
];

// ─── Deduplicate (keep first occurrence) ────────────────────────────────────
const seen = new Set();
const uniqueRoutes = routes.filter(({ path }) => {
  if (seen.has(path)) return false;
  seen.add(path);
  return true;
});

// ─── Build XML ───────────────────────────────────────────────────────────────
const today = new Date().toISOString().split("T")[0];

const urlEntries = uniqueRoutes
  .map(({ path, priority, changefreq }) => {
    const url = `${BASE_URL}${path}`;
    return [
      "  <url>",
      `    <loc>${url}</loc>`,
      `    <lastmod>${today}</lastmod>`,
      `    <changefreq>${changefreq}</changefreq>`,
      `    <priority>${priority}</priority>`,
      "  </url>",
    ].join("\n");
  })
  .join("\n");

const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  urlEntries,
  "</urlset>",
  "",
].join("\n");

writeFileSync(OUTPUT_PATH, xml, "utf-8");
console.log(`✅ sitemap.xml written to ${OUTPUT_PATH}`);
console.log(`   ${uniqueRoutes.length} URLs included (${routes.length - uniqueRoutes.length} duplicates removed)`);
